// Code generated by MockGen. DO NOT EDIT.
// Source: availability_reservation.go
//
// Generated by this command:
//
//	mockgen -source=availability_reservation.go -destination=../data/mock/availability_reservation_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAvailabilityReservationRepository is a mock of AvailabilityReservationRepository interface.
type MockAvailabilityReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvailabilityReservationRepositoryMockRecorder
	isgomock struct{}
}

// MockAvailabilityReservationRepositoryMockRecorder is the mock recorder for MockAvailabilityReservationRepository.
type MockAvailabilityReservationRepositoryMockRecorder struct {
	mock *MockAvailabilityReservationRepository
}

// NewMockAvailabilityReservationRepository creates a new mock instance.
func NewMockAvailabilityReservationRepository(ctrl *gomock.Controller) *MockAvailabilityReservationRepository {
	mock := &MockAvailabilityReservationRepository{ctrl: ctrl}
	mock.recorder = &MockAvailabilityReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvailabilityReservationRepository) EXPECT() *MockAvailabilityReservationRepositoryMockRecorder {
	return m.recorder
}

// CreateAvailabilityMovement mocks base method.
func (m *MockAvailabilityReservationRepository) CreateAvailabilityMovement(ctx context.Context, movement domain.AvailabilityMovement) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvailabilityMovement", ctx, movement)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// CreateAvailabilityMovement indicates an expected call of CreateAvailabilityMovement.
func (mr *MockAvailabilityReservationRepositoryMockRecorder) CreateAvailabilityMovement(ctx, movement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvailabilityMovement", reflect.TypeOf((*MockAvailabilityReservationRepository)(nil).CreateAvailabilityMovement), ctx, movement)
}

// LockProductById mocks base method.
func (m *MockAvailabilityReservationRepository) LockProductById(ctx context.Context, id int64) (domain.Product, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockProductById", ctx, id)
	ret0, _ := ret[0].(domain.Product)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// LockProductById indicates an expected call of LockProductById.
func (mr *MockAvailabilityReservationRepositoryMockRecorder) LockProductById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockProductById", reflect.TypeOf((*MockAvailabilityReservationRepository)(nil).LockProductById), ctx, id)
}

// LockVariantById mocks base method.
func (m *MockAvailabilityReservationRepository) LockVariantById(ctx context.Context, id int64) (domain.Variant, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockVariantById", ctx, id)
	ret0, _ := ret[0].(domain.Variant)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// LockVariantById indicates an expected call of LockVariantById.
func (mr *MockAvailabilityReservationRepositoryMockRecorder) LockVariantById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockVariantById", reflect.TypeOf((*MockAvailabilityReservationRepository)(nil).LockVariantById), ctx, id)
}

// UpdateProductAvailableQuantity mocks base method.
func (m *MockAvailabilityReservationRepository) UpdateProductAvailableQuantity(ctx context.Context, id int64, quantity int) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductAvailableQuantity", ctx, id, quantity)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// UpdateProductAvailableQuantity indicates an expected call of UpdateProductAvailableQuantity.
func (mr *MockAvailabilityReservationRepositoryMockRecorder) UpdateProductAvailableQuantity(ctx, id, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductAvailableQuantity", reflect.TypeOf((*MockAvailabilityReservationRepository)(nil).UpdateProductAvailableQuantity), ctx, id, quantity)
}

// UpdateVariantAvailableQuantity mocks base method.
func (m *MockAvailabilityReservationRepository) UpdateVariantAvailableQuantity(ctx context.Context, id int64, quantity int) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariantAvailableQuantity", ctx, id, quantity)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// UpdateVariantAvailableQuantity indicates an expected call of UpdateVariantAvailableQuantity.
func (mr *MockAvailabilityReservationRepositoryMockRecorder) UpdateVariantAvailableQuantity(ctx, id, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariantAvailableQuantity", reflect.TypeOf((*MockAvailabilityReservationRepository)(nil).UpdateVariantAvailableQuantity), ctx, id, quantity)
}
