// Code generated by MockGen. DO NOT EDIT.
// Source: availability_repository.go
//
// Generated by this command:
//
//	mockgen -source=availability_repository.go -destination=../data/mock/availability_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAvailabilityRepository is a mock of AvailabilityRepository interface.
type MockAvailabilityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAvailabilityRepositoryMockRecorder
	isgomock struct{}
}

// MockAvailabilityRepositoryMockRecorder is the mock recorder for MockAvailabilityRepository.
type MockAvailabilityRepositoryMockRecorder struct {
	mock *MockAvailabilityRepository
}

// NewMockAvailabilityRepository creates a new mock instance.
func NewMockAvailabilityRepository(ctrl *gomock.Controller) *MockAvailabilityRepository {
	mock := &MockAvailabilityRepository{ctrl: ctrl}
	mock.recorder = &MockAvailabilityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvailabilityRepository) EXPECT() *MockAvailabilityRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockAvailabilityRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockAvailabilityRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockAvailabilityRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateAvailabilityMovement mocks base method.
func (m *MockAvailabilityRepository) CreateAvailabilityMovement(ctx context.Context, movement domain.AvailabilityMovement) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvailabilityMovement", ctx, movement)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// CreateAvailabilityMovement indicates an expected call of CreateAvailabilityMovement.
func (mr *MockAvailabilityRepositoryMockRecorder) CreateAvailabilityMovement(ctx, movement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvailabilityMovement", reflect.TypeOf((*MockAvailabilityRepository)(nil).CreateAvailabilityMovement), ctx, movement)
}

// GetAvailabilityMovementList mocks base method.
func (m *MockAvailabilityRepository) GetAvailabilityMovementList(ctx context.Context, level domain.AvailabilityMovementLevel, id int64, skip, limit int) ([]domain.AvailabilityMovement, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailabilityMovementList", ctx, level, id, skip, limit)
	ret0, _ := ret[0].([]domain.AvailabilityMovement)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetAvailabilityMovementList indicates an expected call of GetAvailabilityMovementList.
func (mr *MockAvailabilityRepositoryMockRecorder) GetAvailabilityMovementList(ctx, level, id, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailabilityMovementList", reflect.TypeOf((*MockAvailabilityRepository)(nil).GetAvailabilityMovementList), ctx, level, id, skip, limit)
}

// GetAvailabilityMovementListTotal mocks base method.
func (m *MockAvailabilityRepository) GetAvailabilityMovementListTotal(ctx context.Context, level domain.AvailabilityMovementLevel, id int64) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailabilityMovementListTotal", ctx, level, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetAvailabilityMovementListTotal indicates an expected call of GetAvailabilityMovementListTotal.
func (mr *MockAvailabilityRepositoryMockRecorder) GetAvailabilityMovementListTotal(ctx, level, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailabilityMovementListTotal", reflect.TypeOf((*MockAvailabilityRepository)(nil).GetAvailabilityMovementListTotal), ctx, level, id)
}

// UpdateProductAvailability mocks base method.
func (m *MockAvailabilityRepository) UpdateProductAvailability(ctx context.Context, productId int64, isAvailable *bool, availableQuantity *int) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductAvailability", ctx, productId, isAvailable, availableQuantity)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// UpdateProductAvailability indicates an expected call of UpdateProductAvailability.
func (mr *MockAvailabilityRepositoryMockRecorder) UpdateProductAvailability(ctx, productId, isAvailable, availableQuantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductAvailability", reflect.TypeOf((*MockAvailabilityRepository)(nil).UpdateProductAvailability), ctx, productId, isAvailable, availableQuantity)
}

// UpdateVariantAvailability mocks base method.
func (m *MockAvailabilityRepository) UpdateVariantAvailability(ctx context.Context, variantId int64, isAvailable *bool, availableQuantity *int) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariantAvailability", ctx, variantId, isAvailable, availableQuantity)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// UpdateVariantAvailability indicates an expected call of UpdateVariantAvailability.
func (mr *MockAvailabilityRepositoryMockRecorder) UpdateVariantAvailability(ctx, variantId, isAvailable, availableQuantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariantAvailability", reflect.TypeOf((*MockAvailabilityRepository)(nil).UpdateVariantAvailability), ctx, variantId, isAvailable, availableQuantity)
}
