// Code generated by MockGen. DO NOT EDIT.
// Source: budget_repository.go
//
// Generated by this command:
//
//	mockgen -source=budget_repository.go -destination=../data/mock/budget_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBudgetRepository is a mock of BudgetRepository interface.
type MockBudgetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetRepositoryMockRecorder
	isgomock struct{}
}

// MockBudgetRepositoryMockRecorder is the mock recorder for MockBudgetRepository.
type MockBudgetRepositoryMockRecorder struct {
	mock *MockBudgetRepository
}

// NewMockBudgetRepository creates a new mock instance.
func NewMockBudgetRepository(ctrl *gomock.Controller) *MockBudgetRepository {
	mock := &MockBudgetRepository{ctrl: ctrl}
	mock.recorder = &MockBudgetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetRepository) EXPECT() *MockBudgetRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockBudgetRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockBudgetRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockBudgetRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateBudget mocks base method.
func (m *MockBudgetRepository) CreateBudget(ctx context.Context, budget domain.Budget) (domain.Budget, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBudget", ctx, budget)
	ret0, _ := ret[0].(domain.Budget)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateBudget indicates an expected call of CreateBudget.
func (mr *MockBudgetRepositoryMockRecorder) CreateBudget(ctx, budget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBudget", reflect.TypeOf((*MockBudgetRepository)(nil).CreateBudget), ctx, budget)
}

// DeleteBudgetById mocks base method.
func (m *MockBudgetRepository) DeleteBudgetById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBudgetById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteBudgetById indicates an expected call of DeleteBudgetById.
func (mr *MockBudgetRepositoryMockRecorder) DeleteBudgetById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBudgetById", reflect.TypeOf((*MockBudgetRepository)(nil).DeleteBudgetById), ctx, id)
}

// GetBudgetById mocks base method.
func (m *MockBudgetRepository) GetBudgetById(ctx context.Context, id int64) (domain.Budget, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgetById", ctx, id)
	ret0, _ := ret[0].(domain.Budget)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetBudgetById indicates an expected call of GetBudgetById.
func (mr *MockBudgetRepositoryMockRecorder) GetBudgetById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgetById", reflect.TypeOf((*MockBudgetRepository)(nil).GetBudgetById), ctx, id)
}

// GetBudgetList mocks base method.
func (m *MockBudgetRepository) GetBudgetList(ctx context.Context) ([]domain.Budget, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgetList", ctx)
	ret0, _ := ret[0].([]domain.Budget)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetBudgetList indicates an expected call of GetBudgetList.
func (mr *MockBudgetRepositoryMockRecorder) GetBudgetList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgetList", reflect.TypeOf((*MockBudgetRepository)(nil).GetBudgetList), ctx)
}

// UpdateBudgetById mocks base method.
func (m *MockBudgetRepository) UpdateBudgetById(ctx context.Context, budget domain.Budget, id int64) (domain.Budget, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBudgetById", ctx, budget, id)
	ret0, _ := ret[0].(domain.Budget)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateBudgetById indicates an expected call of UpdateBudgetById.
func (mr *MockBudgetRepositoryMockRecorder) UpdateBudgetById(ctx, budget, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBudgetById", reflect.TypeOf((*MockBudgetRepository)(nil).UpdateBudgetById), ctx, budget, id)
}
