// Code generated by MockGen. DO NOT EDIT.
// Source: calculation_repository.go
//
// Generated by this command:
//
//	mockgen -source=calculation_repository.go -destination=../data/mock/calculation_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCalculationRepository is a mock of CalculationRepository interface.
type MockCalculationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCalculationRepositoryMockRecorder
	isgomock struct{}
}

// MockCalculationRepositoryMockRecorder is the mock recorder for MockCalculationRepository.
type MockCalculationRepositoryMockRecorder struct {
	mock *MockCalculationRepository
}

// NewMockCalculationRepository creates a new mock instance.
func NewMockCalculationRepository(ctrl *gomock.Controller) *MockCalculationRepository {
	mock := &MockCalculationRepository{ctrl: ctrl}
	mock.recorder = &MockCalculationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalculationRepository) EXPECT() *MockCalculationRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockCalculationRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockCalculationRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockCalculationRepository)(nil).BeginTransaction), ctx, callback)
}

// CompleteCalculationById mocks base method.
func (m *MockCalculationRepository) CompleteCalculationById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCalculationById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// CompleteCalculationById indicates an expected call of CompleteCalculationById.
func (mr *MockCalculationRepositoryMockRecorder) CompleteCalculationById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCalculationById", reflect.TypeOf((*MockCalculationRepository)(nil).CompleteCalculationById), ctx, id)
}

// CreateCalculation mocks base method.
func (m *MockCalculationRepository) CreateCalculation(ctx context.Context, calculation domain.Calculation) (domain.Calculation, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCalculation", ctx, calculation)
	ret0, _ := ret[0].(domain.Calculation)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateCalculation indicates an expected call of CreateCalculation.
func (mr *MockCalculationRepositoryMockRecorder) CreateCalculation(ctx, calculation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCalculation", reflect.TypeOf((*MockCalculationRepository)(nil).CreateCalculation), ctx, calculation)
}

// DeleteCalculationById mocks base method.
func (m *MockCalculationRepository) DeleteCalculationById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCalculationById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteCalculationById indicates an expected call of DeleteCalculationById.
func (mr *MockCalculationRepositoryMockRecorder) DeleteCalculationById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCalculationById", reflect.TypeOf((*MockCalculationRepository)(nil).DeleteCalculationById), ctx, id)
}

// GetCalculationById mocks base method.
func (m *MockCalculationRepository) GetCalculationById(ctx context.Context, id int64) (domain.Calculation, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCalculationById", ctx, id)
	ret0, _ := ret[0].(domain.Calculation)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetCalculationById indicates an expected call of GetCalculationById.
func (mr *MockCalculationRepositoryMockRecorder) GetCalculationById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCalculationById", reflect.TypeOf((*MockCalculationRepository)(nil).GetCalculationById), ctx, id)
}

// GetCalculationList mocks base method.
func (m *MockCalculationRepository) GetCalculationList(ctx context.Context, sortBy domain.SortBy, order domain.Order, skip, limit int) ([]domain.Calculation, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCalculationList", ctx, sortBy, order, skip, limit)
	ret0, _ := ret[0].([]domain.Calculation)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetCalculationList indicates an expected call of GetCalculationList.
func (mr *MockCalculationRepositoryMockRecorder) GetCalculationList(ctx, sortBy, order, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCalculationList", reflect.TypeOf((*MockCalculationRepository)(nil).GetCalculationList), ctx, sortBy, order, skip, limit)
}

// UpdateCalculationById mocks base method.
func (m *MockCalculationRepository) UpdateCalculationById(ctx context.Context, calculation domain.Calculation, id int64) (domain.Calculation, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCalculationById", ctx, calculation, id)
	ret0, _ := ret[0].(domain.Calculation)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateCalculationById indicates an expected call of UpdateCalculationById.
func (mr *MockCalculationRepositoryMockRecorder) UpdateCalculationById(ctx, calculation, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCalculationById", reflect.TypeOf((*MockCalculationRepository)(nil).UpdateCalculationById), ctx, calculation, id)
}
