// Code generated by MockGen. DO NOT EDIT.
// Source: cart_repository.go
//
// Generated by this command:
//
//	mockgen -source=cart_repository.go -destination=../data/mock/cart_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCartRepository is a mock of CartRepository interface.
type MockCartRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryMockRecorder
	isgomock struct{}
}

// MockCartRepositoryMockRecorder is the mock recorder for MockCartRepository.
type MockCartRepositoryMockRecorder struct {
	mock *MockCartRepository
}

// NewMockCartRepository creates a new mock instance.
func NewMockCartRepository(ctrl *gomock.Controller) *MockCartRepository {
	mock := &MockCartRepository{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepository) EXPECT() *MockCartRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockCartRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockCartRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockCartRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateCart mocks base method.
func (m *MockCartRepository) CreateCart(ctx context.Context, cart domain.Cart) (domain.Cart, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", ctx, cart)
	ret0, _ := ret[0].(domain.Cart)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockCartRepositoryMockRecorder) CreateCart(ctx, cart any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockCartRepository)(nil).CreateCart), ctx, cart)
}

// CreateCartItem mocks base method.
func (m *MockCartRepository) CreateCartItem(ctx context.Context, cartItem domain.CartItem) (domain.CartItem, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCartItem", ctx, cartItem)
	ret0, _ := ret[0].(domain.CartItem)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateCartItem indicates an expected call of CreateCartItem.
func (mr *MockCartRepositoryMockRecorder) CreateCartItem(ctx, cartItem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCartItem", reflect.TypeOf((*MockCartRepository)(nil).CreateCartItem), ctx, cartItem)
}

// DeleteCartItemById mocks base method.
func (m *MockCartRepository) DeleteCartItemById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItemById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteCartItemById indicates an expected call of DeleteCartItemById.
func (mr *MockCartRepositoryMockRecorder) DeleteCartItemById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItemById", reflect.TypeOf((*MockCartRepository)(nil).DeleteCartItemById), ctx, id)
}

// DeleteCartItemsByCartId mocks base method.
func (m *MockCartRepository) DeleteCartItemsByCartId(ctx context.Context, cartId int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItemsByCartId", ctx, cartId)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteCartItemsByCartId indicates an expected call of DeleteCartItemsByCartId.
func (mr *MockCartRepositoryMockRecorder) DeleteCartItemsByCartId(ctx, cartId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItemsByCartId", reflect.TypeOf((*MockCartRepository)(nil).DeleteCartItemsByCartId), ctx, cartId)
}

// GetActiveCartBySessionId mocks base method.
func (m *MockCartRepository) GetActiveCartBySessionId(ctx context.Context, sessionId string) (domain.Cart, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveCartBySessionId", ctx, sessionId)
	ret0, _ := ret[0].(domain.Cart)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetActiveCartBySessionId indicates an expected call of GetActiveCartBySessionId.
func (mr *MockCartRepositoryMockRecorder) GetActiveCartBySessionId(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveCartBySessionId", reflect.TypeOf((*MockCartRepository)(nil).GetActiveCartBySessionId), ctx, sessionId)
}

// GetCartById mocks base method.
func (m *MockCartRepository) GetCartById(ctx context.Context, id int64) (domain.Cart, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartById", ctx, id)
	ret0, _ := ret[0].(domain.Cart)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetCartById indicates an expected call of GetCartById.
func (mr *MockCartRepositoryMockRecorder) GetCartById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartById", reflect.TypeOf((*MockCartRepository)(nil).GetCartById), ctx, id)
}

// GetCartItemById mocks base method.
func (m *MockCartRepository) GetCartItemById(ctx context.Context, id int64) (domain.CartItem, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemById", ctx, id)
	ret0, _ := ret[0].(domain.CartItem)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetCartItemById indicates an expected call of GetCartItemById.
func (mr *MockCartRepositoryMockRecorder) GetCartItemById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemById", reflect.TypeOf((*MockCartRepository)(nil).GetCartItemById), ctx, id)
}

// UpdateCartById mocks base method.
func (m *MockCartRepository) UpdateCartById(ctx context.Context, cart domain.Cart, id int64) (domain.Cart, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartById", ctx, cart, id)
	ret0, _ := ret[0].(domain.Cart)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateCartById indicates an expected call of UpdateCartById.
func (mr *MockCartRepositoryMockRecorder) UpdateCartById(ctx, cart, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartById", reflect.TypeOf((*MockCartRepository)(nil).UpdateCartById), ctx, cart, id)
}

// UpdateCartItemById mocks base method.
func (m *MockCartRepository) UpdateCartItemById(ctx context.Context, cartItem domain.CartItem, id int64) (domain.CartItem, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItemById", ctx, cartItem, id)
	ret0, _ := ret[0].(domain.CartItem)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateCartItemById indicates an expected call of UpdateCartItemById.
func (mr *MockCartRepositoryMockRecorder) UpdateCartItemById(ctx, cartItem, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItemById", reflect.TypeOf((*MockCartRepository)(nil).UpdateCartItemById), ctx, cartItem, id)
}
