// Code generated by MockGen. DO NOT EDIT.
// Source: checklist_session_repository.go
//
// Generated by this command:
//
//	mockgen -source=checklist_session_repository.go -destination=../data/mock/checklist_session_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockChecklistSessionRepository is a mock of ChecklistSessionRepository interface.
type MockChecklistSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChecklistSessionRepositoryMockRecorder
}

// MockChecklistSessionRepositoryMockRecorder is the mock recorder for MockChecklistSessionRepository.
type MockChecklistSessionRepositoryMockRecorder struct {
	mock *MockChecklistSessionRepository
}

// NewMockChecklistSessionRepository creates a new mock instance.
func NewMockChecklistSessionRepository(ctrl *gomock.Controller) *MockChecklistSessionRepository {
	mock := &MockChecklistSessionRepository{ctrl: ctrl}
	mock.recorder = &MockChecklistSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecklistSessionRepository) EXPECT() *MockChecklistSessionRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockChecklistSessionRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockChecklistSessionRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockChecklistSessionRepository)(nil).BeginTransaction), ctx, callback)
}

// GetChecklistSessionById mocks base method.
func (m *MockChecklistSessionRepository) GetChecklistSessionById(ctx context.Context, id int64) (domain.ChecklistSession, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistSessionById", ctx, id)
	ret0, _ := ret[0].(domain.ChecklistSession)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistSessionById indicates an expected call of GetChecklistSessionById.
func (mr *MockChecklistSessionRepositoryMockRecorder) GetChecklistSessionById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistSessionById", reflect.TypeOf((*MockChecklistSessionRepository)(nil).GetChecklistSessionById), ctx, id)
}

// GetChecklistSessionByTemplateAndDate mocks base method.
func (m *MockChecklistSessionRepository) GetChecklistSessionByTemplateAndDate(ctx context.Context, templateId int64, date string) (domain.ChecklistSession, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistSessionByTemplateAndDate", ctx, templateId, date)
	ret0, _ := ret[0].(domain.ChecklistSession)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistSessionByTemplateAndDate indicates an expected call of GetChecklistSessionByTemplateAndDate.
func (mr *MockChecklistSessionRepositoryMockRecorder) GetChecklistSessionByTemplateAndDate(ctx, templateId, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistSessionByTemplateAndDate", reflect.TypeOf((*MockChecklistSessionRepository)(nil).GetChecklistSessionByTemplateAndDate), ctx, templateId, date)
}

// CreateChecklistSession mocks base method.
func (m *MockChecklistSessionRepository) CreateChecklistSession(ctx context.Context, session domain.ChecklistSession) (domain.ChecklistSession, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChecklistSession", ctx, session)
	ret0, _ := ret[0].(domain.ChecklistSession)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateChecklistSession indicates an expected call of CreateChecklistSession.
func (mr *MockChecklistSessionRepositoryMockRecorder) CreateChecklistSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChecklistSession", reflect.TypeOf((*MockChecklistSessionRepository)(nil).CreateChecklistSession), ctx, session)
}

// DeleteChecklistSessionById mocks base method.
func (m *MockChecklistSessionRepository) DeleteChecklistSessionById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChecklistSessionById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteChecklistSessionById indicates an expected call of DeleteChecklistSessionById.
func (mr *MockChecklistSessionRepositoryMockRecorder) DeleteChecklistSessionById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChecklistSessionById", reflect.TypeOf((*MockChecklistSessionRepository)(nil).DeleteChecklistSessionById), ctx, id)
}

// GetChecklistSessionItemById mocks base method.
func (m *MockChecklistSessionRepository) GetChecklistSessionItemById(ctx context.Context, id int64) (domain.ChecklistSessionItem, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistSessionItemById", ctx, id)
	ret0, _ := ret[0].(domain.ChecklistSessionItem)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistSessionItemById indicates an expected call of GetChecklistSessionItemById.
func (mr *MockChecklistSessionRepositoryMockRecorder) GetChecklistSessionItemById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistSessionItemById", reflect.TypeOf((*MockChecklistSessionRepository)(nil).GetChecklistSessionItemById), ctx, id)
}

// UpdateChecklistSessionItemCompletedAt mocks base method.
func (m *MockChecklistSessionRepository) UpdateChecklistSessionItemCompletedAt(ctx context.Context, itemId int64, completedAt *time.Time) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChecklistSessionItemCompletedAt", ctx, itemId, completedAt)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// UpdateChecklistSessionItemCompletedAt indicates an expected call of UpdateChecklistSessionItemCompletedAt.
func (mr *MockChecklistSessionRepositoryMockRecorder) UpdateChecklistSessionItemCompletedAt(ctx, itemId, completedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChecklistSessionItemCompletedAt", reflect.TypeOf((*MockChecklistSessionRepository)(nil).UpdateChecklistSessionItemCompletedAt), ctx, itemId, completedAt)
}

// UpdateChecklistSessionCompletedAt mocks base method.
func (m *MockChecklistSessionRepository) UpdateChecklistSessionCompletedAt(ctx context.Context, sessionId int64, completedAt *time.Time) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChecklistSessionCompletedAt", ctx, sessionId, completedAt)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// UpdateChecklistSessionCompletedAt indicates an expected call of UpdateChecklistSessionCompletedAt.
func (mr *MockChecklistSessionRepositoryMockRecorder) UpdateChecklistSessionCompletedAt(ctx, sessionId, completedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChecklistSessionCompletedAt", reflect.TypeOf((*MockChecklistSessionRepository)(nil).UpdateChecklistSessionCompletedAt), ctx, sessionId, completedAt)
}

// GetChecklistSessionSubItemById mocks base method.
func (m *MockChecklistSessionRepository) GetChecklistSessionSubItemById(ctx context.Context, id int64) (domain.ChecklistSessionSubItem, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistSessionSubItemById", ctx, id)
	ret0, _ := ret[0].(domain.ChecklistSessionSubItem)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistSessionSubItemById indicates an expected call of GetChecklistSessionSubItemById.
func (mr *MockChecklistSessionRepositoryMockRecorder) GetChecklistSessionSubItemById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistSessionSubItemById", reflect.TypeOf((*MockChecklistSessionRepository)(nil).GetChecklistSessionSubItemById), ctx, id)
}

// UpdateChecklistSessionSubItemCompletedAt mocks base method.
func (m *MockChecklistSessionRepository) UpdateChecklistSessionSubItemCompletedAt(ctx context.Context, subItemId int64, completedAt *time.Time) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChecklistSessionSubItemCompletedAt", ctx, subItemId, completedAt)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// UpdateChecklistSessionSubItemCompletedAt indicates an expected call of UpdateChecklistSessionSubItemCompletedAt.
func (mr *MockChecklistSessionRepositoryMockRecorder) UpdateChecklistSessionSubItemCompletedAt(ctx, subItemId, completedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChecklistSessionSubItemCompletedAt", reflect.TypeOf((*MockChecklistSessionRepository)(nil).UpdateChecklistSessionSubItemCompletedAt), ctx, subItemId, completedAt)
}

// GetChecklistSessionItemsBySessionId mocks base method.
func (m *MockChecklistSessionRepository) GetChecklistSessionItemsBySessionId(ctx context.Context, sessionId int64) ([]domain.ChecklistSessionItem, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistSessionItemsBySessionId", ctx, sessionId)
	ret0, _ := ret[0].([]domain.ChecklistSessionItem)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistSessionItemsBySessionId indicates an expected call of GetChecklistSessionItemsBySessionId.
func (mr *MockChecklistSessionRepositoryMockRecorder) GetChecklistSessionItemsBySessionId(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistSessionItemsBySessionId", reflect.TypeOf((*MockChecklistSessionRepository)(nil).GetChecklistSessionItemsBySessionId), ctx, sessionId)
}

// GetChecklistSessionSubItemsByItemId mocks base method.
func (m *MockChecklistSessionRepository) GetChecklistSessionSubItemsByItemId(ctx context.Context, itemId int64) ([]domain.ChecklistSessionSubItem, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistSessionSubItemsByItemId", ctx, itemId)
	ret0, _ := ret[0].([]domain.ChecklistSessionSubItem)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistSessionSubItemsByItemId indicates an expected call of GetChecklistSessionSubItemsByItemId.
func (mr *MockChecklistSessionRepositoryMockRecorder) GetChecklistSessionSubItemsByItemId(ctx, itemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistSessionSubItemsByItemId", reflect.TypeOf((*MockChecklistSessionRepository)(nil).GetChecklistSessionSubItemsByItemId), ctx, itemId)
}
