// Code generated by MockGen. DO NOT EDIT.
// Source: checklist_template_repository.go
//
// Generated by this command:
//
//	mockgen -source=checklist_template_repository.go -destination=../data/mock/checklist_template_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChecklistTemplateRepository is a mock of ChecklistTemplateRepository interface.
type MockChecklistTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChecklistTemplateRepositoryMockRecorder
}

// MockChecklistTemplateRepositoryMockRecorder is the mock recorder for MockChecklistTemplateRepository.
type MockChecklistTemplateRepositoryMockRecorder struct {
	mock *MockChecklistTemplateRepository
}

// NewMockChecklistTemplateRepository creates a new mock instance.
func NewMockChecklistTemplateRepository(ctrl *gomock.Controller) *MockChecklistTemplateRepository {
	mock := &MockChecklistTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockChecklistTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecklistTemplateRepository) EXPECT() *MockChecklistTemplateRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockChecklistTemplateRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockChecklistTemplateRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockChecklistTemplateRepository)(nil).BeginTransaction), ctx, callback)
}

// GetChecklistTemplateList mocks base method.
func (m *MockChecklistTemplateRepository) GetChecklistTemplateList(ctx context.Context, query string, skip int, limit int) ([]domain.ChecklistTemplate, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistTemplateList", ctx, query, skip, limit)
	ret0, _ := ret[0].([]domain.ChecklistTemplate)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistTemplateList indicates an expected call of GetChecklistTemplateList.
func (mr *MockChecklistTemplateRepositoryMockRecorder) GetChecklistTemplateList(ctx, query, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistTemplateList", reflect.TypeOf((*MockChecklistTemplateRepository)(nil).GetChecklistTemplateList), ctx, query, skip, limit)
}

// GetChecklistTemplateListTotal mocks base method.
func (m *MockChecklistTemplateRepository) GetChecklistTemplateListTotal(ctx context.Context, query string) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistTemplateListTotal", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistTemplateListTotal indicates an expected call of GetChecklistTemplateListTotal.
func (mr *MockChecklistTemplateRepositoryMockRecorder) GetChecklistTemplateListTotal(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistTemplateListTotal", reflect.TypeOf((*MockChecklistTemplateRepository)(nil).GetChecklistTemplateListTotal), ctx, query)
}

// GetChecklistTemplateById mocks base method.
func (m *MockChecklistTemplateRepository) GetChecklistTemplateById(ctx context.Context, id int64) (domain.ChecklistTemplate, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistTemplateById", ctx, id)
	ret0, _ := ret[0].(domain.ChecklistTemplate)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistTemplateById indicates an expected call of GetChecklistTemplateById.
func (mr *MockChecklistTemplateRepositoryMockRecorder) GetChecklistTemplateById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistTemplateById", reflect.TypeOf((*MockChecklistTemplateRepository)(nil).GetChecklistTemplateById), ctx, id)
}

// GetChecklistTemplateByName mocks base method.
func (m *MockChecklistTemplateRepository) GetChecklistTemplateByName(ctx context.Context, name string) (domain.ChecklistTemplate, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChecklistTemplateByName", ctx, name)
	ret0, _ := ret[0].(domain.ChecklistTemplate)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetChecklistTemplateByName indicates an expected call of GetChecklistTemplateByName.
func (mr *MockChecklistTemplateRepositoryMockRecorder) GetChecklistTemplateByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChecklistTemplateByName", reflect.TypeOf((*MockChecklistTemplateRepository)(nil).GetChecklistTemplateByName), ctx, name)
}

// CreateChecklistTemplate mocks base method.
func (m *MockChecklistTemplateRepository) CreateChecklistTemplate(ctx context.Context, template domain.ChecklistTemplate) (domain.ChecklistTemplate, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChecklistTemplate", ctx, template)
	ret0, _ := ret[0].(domain.ChecklistTemplate)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateChecklistTemplate indicates an expected call of CreateChecklistTemplate.
func (mr *MockChecklistTemplateRepositoryMockRecorder) CreateChecklistTemplate(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChecklistTemplate", reflect.TypeOf((*MockChecklistTemplateRepository)(nil).CreateChecklistTemplate), ctx, template)
}

// UpdateChecklistTemplateById mocks base method.
func (m *MockChecklistTemplateRepository) UpdateChecklistTemplateById(ctx context.Context, template domain.ChecklistTemplate, id int64) (domain.ChecklistTemplate, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChecklistTemplateById", ctx, template, id)
	ret0, _ := ret[0].(domain.ChecklistTemplate)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateChecklistTemplateById indicates an expected call of UpdateChecklistTemplateById.
func (mr *MockChecklistTemplateRepositoryMockRecorder) UpdateChecklistTemplateById(ctx, template, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChecklistTemplateById", reflect.TypeOf((*MockChecklistTemplateRepository)(nil).UpdateChecklistTemplateById), ctx, template, id)
}

// DeleteChecklistTemplateById mocks base method.
func (m *MockChecklistTemplateRepository) DeleteChecklistTemplateById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChecklistTemplateById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteChecklistTemplateById indicates an expected call of DeleteChecklistTemplateById.
func (mr *MockChecklistTemplateRepositoryMockRecorder) DeleteChecklistTemplateById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChecklistTemplateById", reflect.TypeOf((*MockChecklistTemplateRepository)(nil).DeleteChecklistTemplateById), ctx, id)
}
