// Code generated by MockGen. DO NOT EDIT.
// Source: coupon_repository.go
//
// Generated by this command:
//
//	mockgen -source=coupon_repository.go -destination=../data/mock/coupon_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCouponRepository is a mock of CouponRepository interface.
type MockCouponRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCouponRepositoryMockRecorder
	isgomock struct{}
}

// MockCouponRepositoryMockRecorder is the mock recorder for MockCouponRepository.
type MockCouponRepositoryMockRecorder struct {
	mock *MockCouponRepository
}

// NewMockCouponRepository creates a new mock instance.
func NewMockCouponRepository(ctrl *gomock.Controller) *MockCouponRepository {
	mock := &MockCouponRepository{ctrl: ctrl}
	mock.recorder = &MockCouponRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCouponRepository) EXPECT() *MockCouponRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockCouponRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockCouponRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockCouponRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateCoupon mocks base method.
func (m *MockCouponRepository) CreateCoupon(ctx context.Context, coupon domain.Coupon) (domain.Coupon, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCoupon", ctx, coupon)
	ret0, _ := ret[0].(domain.Coupon)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateCoupon indicates an expected call of CreateCoupon.
func (mr *MockCouponRepositoryMockRecorder) CreateCoupon(ctx, coupon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCoupon", reflect.TypeOf((*MockCouponRepository)(nil).CreateCoupon), ctx, coupon)
}

// DeleteCouponById mocks base method.
func (m *MockCouponRepository) DeleteCouponById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCouponById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteCouponById indicates an expected call of DeleteCouponById.
func (mr *MockCouponRepositoryMockRecorder) DeleteCouponById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCouponById", reflect.TypeOf((*MockCouponRepository)(nil).DeleteCouponById), ctx, id)
}

// GetCouponById mocks base method.
func (m *MockCouponRepository) GetCouponById(ctx context.Context, id int64) (domain.Coupon, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCouponById", ctx, id)
	ret0, _ := ret[0].(domain.Coupon)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetCouponById indicates an expected call of GetCouponById.
func (mr *MockCouponRepositoryMockRecorder) GetCouponById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCouponById", reflect.TypeOf((*MockCouponRepository)(nil).GetCouponById), ctx, id)
}

// GetCouponList mocks base method.
func (m *MockCouponRepository) GetCouponList(ctx context.Context) ([]domain.Coupon, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCouponList", ctx)
	ret0, _ := ret[0].([]domain.Coupon)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetCouponList indicates an expected call of GetCouponList.
func (mr *MockCouponRepositoryMockRecorder) GetCouponList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCouponList", reflect.TypeOf((*MockCouponRepository)(nil).GetCouponList), ctx)
}

// UpdateCouponById mocks base method.
func (m *MockCouponRepository) UpdateCouponById(ctx context.Context, coupon domain.Coupon, id int64) (domain.Coupon, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCouponById", ctx, coupon, id)
	ret0, _ := ret[0].(domain.Coupon)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateCouponById indicates an expected call of UpdateCouponById.
func (mr *MockCouponRepositoryMockRecorder) UpdateCouponById(ctx, coupon, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCouponById", reflect.TypeOf((*MockCouponRepository)(nil).UpdateCouponById), ctx, coupon, id)
}
