// Code generated by MockGen. DO NOT EDIT.
// Source: customer_repository.go
//
// Generated by this command:
//
//	mockgen -source=customer_repository.go -destination=../data/mock/customer_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCustomerRepository is a mock of CustomerRepository interface.
type MockCustomerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerRepositoryMockRecorder
	isgomock struct{}
}

// MockCustomerRepositoryMockRecorder is the mock recorder for MockCustomerRepository.
type MockCustomerRepositoryMockRecorder struct {
	mock *MockCustomerRepository
}

// NewMockCustomerRepository creates a new mock instance.
func NewMockCustomerRepository(ctrl *gomock.Controller) *MockCustomerRepository {
	mock := &MockCustomerRepository{ctrl: ctrl}
	mock.recorder = &MockCustomerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerRepository) EXPECT() *MockCustomerRepositoryMockRecorder {
	return m.recorder
}

// GetCustomerBySessionId mocks base method.
func (m *MockCustomerRepository) GetCustomerBySessionId(ctx context.Context, sessionId string) (domain.Customer, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerBySessionId", ctx, sessionId)
	ret0, _ := ret[0].(domain.Customer)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetCustomerBySessionId indicates an expected call of GetCustomerBySessionId.
func (mr *MockCustomerRepositoryMockRecorder) GetCustomerBySessionId(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerBySessionId", reflect.TypeOf((*MockCustomerRepository)(nil).GetCustomerBySessionId), ctx, sessionId)
}

// UpsertCustomerBySessionId mocks base method.
func (m *MockCustomerRepository) UpsertCustomerBySessionId(ctx context.Context, sessionId, name string) (domain.Customer, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCustomerBySessionId", ctx, sessionId, name)
	ret0, _ := ret[0].(domain.Customer)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpsertCustomerBySessionId indicates an expected call of UpsertCustomerBySessionId.
func (mr *MockCustomerRepositoryMockRecorder) UpsertCustomerBySessionId(ctx, sessionId, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCustomerBySessionId", reflect.TypeOf((*MockCustomerRepository)(nil).UpsertCustomerBySessionId), ctx, sessionId, name)
}
