// Code generated by MockGen. DO NOT EDIT.
// Source: expense_repository.go
//
// Generated by this command:
//
//	mockgen -source=expense_repository.go -destination=../data/mock/expense_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExpenseRepository is a mock of ExpenseRepository interface.
type MockExpenseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExpenseRepositoryMockRecorder
	isgomock struct{}
}

// MockExpenseRepositoryMockRecorder is the mock recorder for MockExpenseRepository.
type MockExpenseRepositoryMockRecorder struct {
	mock *MockExpenseRepository
}

// NewMockExpenseRepository creates a new mock instance.
func NewMockExpenseRepository(ctrl *gomock.Controller) *MockExpenseRepository {
	mock := &MockExpenseRepository{ctrl: ctrl}
	mock.recorder = &MockExpenseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenseRepository) EXPECT() *MockExpenseRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockExpenseRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockExpenseRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockExpenseRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateExpense mocks base method.
func (m *MockExpenseRepository) CreateExpense(ctx context.Context, expense domain.Expense) (domain.Expense, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExpense", ctx, expense)
	ret0, _ := ret[0].(domain.Expense)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateExpense indicates an expected call of CreateExpense.
func (mr *MockExpenseRepositoryMockRecorder) CreateExpense(ctx, expense any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExpense", reflect.TypeOf((*MockExpenseRepository)(nil).CreateExpense), ctx, expense)
}

// DeleteExpenseById mocks base method.
func (m *MockExpenseRepository) DeleteExpenseById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpenseById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteExpenseById indicates an expected call of DeleteExpenseById.
func (mr *MockExpenseRepositoryMockRecorder) DeleteExpenseById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpenseById", reflect.TypeOf((*MockExpenseRepository)(nil).DeleteExpenseById), ctx, id)
}

// GetExpenseById mocks base method.
func (m *MockExpenseRepository) GetExpenseById(ctx context.Context, id int64) (domain.Expense, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpenseById", ctx, id)
	ret0, _ := ret[0].(domain.Expense)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetExpenseById indicates an expected call of GetExpenseById.
func (mr *MockExpenseRepositoryMockRecorder) GetExpenseById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpenseById", reflect.TypeOf((*MockExpenseRepository)(nil).GetExpenseById), ctx, id)
}

// GetExpenseList mocks base method.
func (m *MockExpenseRepository) GetExpenseList(ctx context.Context, query string, sortBy domain.SortBy, order domain.Order, skip, limit int, walletId, budgetId *int) ([]domain.Expense, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpenseList", ctx, query, sortBy, order, skip, limit, walletId, budgetId)
	ret0, _ := ret[0].([]domain.Expense)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetExpenseList indicates an expected call of GetExpenseList.
func (mr *MockExpenseRepositoryMockRecorder) GetExpenseList(ctx, query, sortBy, order, skip, limit, walletId, budgetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpenseList", reflect.TypeOf((*MockExpenseRepository)(nil).GetExpenseList), ctx, query, sortBy, order, skip, limit, walletId, budgetId)
}

// GetExpenseListTotal mocks base method.
func (m *MockExpenseRepository) GetExpenseListTotal(ctx context.Context, query string, walletId, budgetId *int) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpenseListTotal", ctx, query, walletId, budgetId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetExpenseListTotal indicates an expected call of GetExpenseListTotal.
func (mr *MockExpenseRepositoryMockRecorder) GetExpenseListTotal(ctx, query, walletId, budgetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpenseListTotal", reflect.TypeOf((*MockExpenseRepository)(nil).GetExpenseListTotal), ctx, query, walletId, budgetId)
}

// UpdateExpenseById mocks base method.
func (m *MockExpenseRepository) UpdateExpenseById(ctx context.Context, expense domain.Expense, id int64) (domain.Expense, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExpenseById", ctx, expense, id)
	ret0, _ := ret[0].(domain.Expense)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateExpenseById indicates an expected call of UpdateExpenseById.
func (mr *MockExpenseRepositoryMockRecorder) UpdateExpenseById(ctx, expense, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpenseById", reflect.TypeOf((*MockExpenseRepository)(nil).UpdateExpenseById), ctx, expense, id)
}
