// Code generated by MockGen. DO NOT EDIT.
// Source: guest_notification_repository.go
//
// Generated by this command:
//
//	mockgen -source=guest_notification_repository.go -destination=../data/mock/guest_notification_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockGuestNotificationRepository is a mock of GuestNotificationRepository interface.
type MockGuestNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGuestNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockGuestNotificationRepositoryMockRecorder is the mock recorder for MockGuestNotificationRepository.
type MockGuestNotificationRepositoryMockRecorder struct {
	mock *MockGuestNotificationRepository
}

// NewMockGuestNotificationRepository creates a new mock instance.
func NewMockGuestNotificationRepository(ctrl *gomock.Controller) *MockGuestNotificationRepository {
	mock := &MockGuestNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockGuestNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuestNotificationRepository) EXPECT() *MockGuestNotificationRepositoryMockRecorder {
	return m.recorder
}

// ClaimPendingGuestNotifications mocks base method.
func (m *MockGuestNotificationRepository) ClaimPendingGuestNotifications(ctx context.Context, limit int) ([]domain.GuestNotification, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingGuestNotifications", ctx, limit)
	ret0, _ := ret[0].([]domain.GuestNotification)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// ClaimPendingGuestNotifications indicates an expected call of ClaimPendingGuestNotifications.
func (mr *MockGuestNotificationRepositoryMockRecorder) ClaimPendingGuestNotifications(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingGuestNotifications", reflect.TypeOf((*MockGuestNotificationRepository)(nil).ClaimPendingGuestNotifications), ctx, limit)
}

// EnqueueForCompletedTransaction mocks base method.
func (m *MockGuestNotificationRepository) EnqueueForCompletedTransaction(ctx context.Context, transaction domain.Transaction, sessionId, whatsappNumber *string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueForCompletedTransaction", ctx, transaction, sessionId, whatsappNumber)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// EnqueueForCompletedTransaction indicates an expected call of EnqueueForCompletedTransaction.
func (mr *MockGuestNotificationRepositoryMockRecorder) EnqueueForCompletedTransaction(ctx, transaction, sessionId, whatsappNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueForCompletedTransaction", reflect.TypeOf((*MockGuestNotificationRepository)(nil).EnqueueForCompletedTransaction), ctx, transaction, sessionId, whatsappNumber)
}

// ExpireStaleSending mocks base method.
func (m *MockGuestNotificationRepository) ExpireStaleSending(ctx context.Context, now time.Time) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireStaleSending", ctx, now)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// ExpireStaleSending indicates an expected call of ExpireStaleSending.
func (mr *MockGuestNotificationRepositoryMockRecorder) ExpireStaleSending(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireStaleSending", reflect.TypeOf((*MockGuestNotificationRepository)(nil).ExpireStaleSending), ctx, now)
}

// MarkGuestNotificationFailed mocks base method.
func (m *MockGuestNotificationRepository) MarkGuestNotificationFailed(ctx context.Context, id int64, detail string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkGuestNotificationFailed", ctx, id, detail)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// MarkGuestNotificationFailed indicates an expected call of MarkGuestNotificationFailed.
func (mr *MockGuestNotificationRepositoryMockRecorder) MarkGuestNotificationFailed(ctx, id, detail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkGuestNotificationFailed", reflect.TypeOf((*MockGuestNotificationRepository)(nil).MarkGuestNotificationFailed), ctx, id, detail)
}

// MarkGuestNotificationSent mocks base method.
func (m *MockGuestNotificationRepository) MarkGuestNotificationSent(ctx context.Context, id int64, providerMessageId string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkGuestNotificationSent", ctx, id, providerMessageId)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// MarkGuestNotificationSent indicates an expected call of MarkGuestNotificationSent.
func (mr *MockGuestNotificationRepositoryMockRecorder) MarkGuestNotificationSent(ctx, id, providerMessageId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkGuestNotificationSent", reflect.TypeOf((*MockGuestNotificationRepository)(nil).MarkGuestNotificationSent), ctx, id, providerMessageId)
}

// MarkGuestNotificationSkipped mocks base method.
func (m *MockGuestNotificationRepository) MarkGuestNotificationSkipped(ctx context.Context, id int64, detail string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkGuestNotificationSkipped", ctx, id, detail)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// MarkGuestNotificationSkipped indicates an expected call of MarkGuestNotificationSkipped.
func (mr *MockGuestNotificationRepositoryMockRecorder) MarkGuestNotificationSkipped(ctx, id, detail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkGuestNotificationSkipped", reflect.TypeOf((*MockGuestNotificationRepository)(nil).MarkGuestNotificationSkipped), ctx, id, detail)
}

// MarkGuestNotificationUnknownOutcome mocks base method.
func (m *MockGuestNotificationRepository) MarkGuestNotificationUnknownOutcome(ctx context.Context, id int64, detail string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkGuestNotificationUnknownOutcome", ctx, id, detail)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// MarkGuestNotificationUnknownOutcome indicates an expected call of MarkGuestNotificationUnknownOutcome.
func (mr *MockGuestNotificationRepositoryMockRecorder) MarkGuestNotificationUnknownOutcome(ctx, id, detail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkGuestNotificationUnknownOutcome", reflect.TypeOf((*MockGuestNotificationRepository)(nil).MarkGuestNotificationUnknownOutcome), ctx, id, detail)
}

// MockGuestNotificationDispatcher is a mock of GuestNotificationDispatcher interface.
type MockGuestNotificationDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockGuestNotificationDispatcherMockRecorder
	isgomock struct{}
}

// MockGuestNotificationDispatcherMockRecorder is the mock recorder for MockGuestNotificationDispatcher.
type MockGuestNotificationDispatcherMockRecorder struct {
	mock *MockGuestNotificationDispatcher
}

// NewMockGuestNotificationDispatcher creates a new mock instance.
func NewMockGuestNotificationDispatcher(ctrl *gomock.Controller) *MockGuestNotificationDispatcher {
	mock := &MockGuestNotificationDispatcher{ctrl: ctrl}
	mock.recorder = &MockGuestNotificationDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuestNotificationDispatcher) EXPECT() *MockGuestNotificationDispatcherMockRecorder {
	return m.recorder
}

// TriggerDispatch mocks base method.
func (m *MockGuestNotificationDispatcher) TriggerDispatch() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerDispatch")
}

// TriggerDispatch indicates an expected call of TriggerDispatch.
func (mr *MockGuestNotificationDispatcherMockRecorder) TriggerDispatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerDispatch", reflect.TypeOf((*MockGuestNotificationDispatcher)(nil).TriggerDispatch))
}
