// Code generated by MockGen. DO NOT EDIT.
// Source: kds_notification_repository.go
//
// Generated by this command:
//
//	mockgen -source=kds_notification_repository.go -destination=../data/mock/kds_notification_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKdsPushGatewayRepository is a mock of KdsPushGatewayRepository interface.
type MockKdsPushGatewayRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKdsPushGatewayRepositoryMockRecorder
	isgomock struct{}
}

// MockKdsPushGatewayRepositoryMockRecorder is the mock recorder for MockKdsPushGatewayRepository.
type MockKdsPushGatewayRepositoryMockRecorder struct {
	mock *MockKdsPushGatewayRepository
}

// NewMockKdsPushGatewayRepository creates a new mock instance.
func NewMockKdsPushGatewayRepository(ctrl *gomock.Controller) *MockKdsPushGatewayRepository {
	mock := &MockKdsPushGatewayRepository{ctrl: ctrl}
	mock.recorder = &MockKdsPushGatewayRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKdsPushGatewayRepository) EXPECT() *MockKdsPushGatewayRepositoryMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockKdsPushGatewayRepository) Send(ctx context.Context, messages []domain.KdsPushMessage) ([]domain.KdsPushReceipt, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, messages)
	ret0, _ := ret[0].([]domain.KdsPushReceipt)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockKdsPushGatewayRepositoryMockRecorder) Send(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockKdsPushGatewayRepository)(nil).Send), ctx, messages)
}

// MockKdsNotificationRepository is a mock of KdsNotificationRepository interface.
type MockKdsNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKdsNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockKdsNotificationRepositoryMockRecorder is the mock recorder for MockKdsNotificationRepository.
type MockKdsNotificationRepositoryMockRecorder struct {
	mock *MockKdsNotificationRepository
}

// NewMockKdsNotificationRepository creates a new mock instance.
func NewMockKdsNotificationRepository(ctrl *gomock.Controller) *MockKdsNotificationRepository {
	mock := &MockKdsNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockKdsNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKdsNotificationRepository) EXPECT() *MockKdsNotificationRepositoryMockRecorder {
	return m.recorder
}

// ClaimPendingKdsNotifications mocks base method.
func (m *MockKdsNotificationRepository) ClaimPendingKdsNotifications(ctx context.Context, limit int) ([]domain.KdsNotification, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingKdsNotifications", ctx, limit)
	ret0, _ := ret[0].([]domain.KdsNotification)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// ClaimPendingKdsNotifications indicates an expected call of ClaimPendingKdsNotifications.
func (mr *MockKdsNotificationRepositoryMockRecorder) ClaimPendingKdsNotifications(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingKdsNotifications", reflect.TypeOf((*MockKdsNotificationRepository)(nil).ClaimPendingKdsNotifications), ctx, limit)
}

// EnqueueForTransaction mocks base method.
func (m *MockKdsNotificationRepository) EnqueueForTransaction(ctx context.Context, transaction domain.Transaction, kind domain.KdsNotificationKind) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueForTransaction", ctx, transaction, kind)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// EnqueueForTransaction indicates an expected call of EnqueueForTransaction.
func (mr *MockKdsNotificationRepositoryMockRecorder) EnqueueForTransaction(ctx, transaction, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueForTransaction", reflect.TypeOf((*MockKdsNotificationRepository)(nil).EnqueueForTransaction), ctx, transaction, kind)
}

// HasNotificationForTransaction mocks base method.
func (m *MockKdsNotificationRepository) HasNotificationForTransaction(ctx context.Context, transactionId int64, kind domain.KdsNotificationKind) (bool, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasNotificationForTransaction", ctx, transactionId, kind)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// HasNotificationForTransaction indicates an expected call of HasNotificationForTransaction.
func (mr *MockKdsNotificationRepositoryMockRecorder) HasNotificationForTransaction(ctx, transactionId, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasNotificationForTransaction", reflect.TypeOf((*MockKdsNotificationRepository)(nil).HasNotificationForTransaction), ctx, transactionId, kind)
}

// MarkKdsNotificationFailed mocks base method.
func (m *MockKdsNotificationRepository) MarkKdsNotificationFailed(ctx context.Context, id int64, detail string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkKdsNotificationFailed", ctx, id, detail)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// MarkKdsNotificationFailed indicates an expected call of MarkKdsNotificationFailed.
func (mr *MockKdsNotificationRepositoryMockRecorder) MarkKdsNotificationFailed(ctx, id, detail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkKdsNotificationFailed", reflect.TypeOf((*MockKdsNotificationRepository)(nil).MarkKdsNotificationFailed), ctx, id, detail)
}

// MarkKdsNotificationSent mocks base method.
func (m *MockKdsNotificationRepository) MarkKdsNotificationSent(ctx context.Context, id int64, detail string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkKdsNotificationSent", ctx, id, detail)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// MarkKdsNotificationSent indicates an expected call of MarkKdsNotificationSent.
func (mr *MockKdsNotificationRepositoryMockRecorder) MarkKdsNotificationSent(ctx, id, detail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkKdsNotificationSent", reflect.TypeOf((*MockKdsNotificationRepository)(nil).MarkKdsNotificationSent), ctx, id, detail)
}

// MarkKdsNotificationSkipped mocks base method.
func (m *MockKdsNotificationRepository) MarkKdsNotificationSkipped(ctx context.Context, id int64, detail string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkKdsNotificationSkipped", ctx, id, detail)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// MarkKdsNotificationSkipped indicates an expected call of MarkKdsNotificationSkipped.
func (mr *MockKdsNotificationRepositoryMockRecorder) MarkKdsNotificationSkipped(ctx, id, detail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkKdsNotificationSkipped", reflect.TypeOf((*MockKdsNotificationRepository)(nil).MarkKdsNotificationSkipped), ctx, id, detail)
}

// MockKdsNotificationDispatcher is a mock of KdsNotificationDispatcher interface.
type MockKdsNotificationDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockKdsNotificationDispatcherMockRecorder
	isgomock struct{}
}

// MockKdsNotificationDispatcherMockRecorder is the mock recorder for MockKdsNotificationDispatcher.
type MockKdsNotificationDispatcherMockRecorder struct {
	mock *MockKdsNotificationDispatcher
}

// NewMockKdsNotificationDispatcher creates a new mock instance.
func NewMockKdsNotificationDispatcher(ctrl *gomock.Controller) *MockKdsNotificationDispatcher {
	mock := &MockKdsNotificationDispatcher{ctrl: ctrl}
	mock.recorder = &MockKdsNotificationDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKdsNotificationDispatcher) EXPECT() *MockKdsNotificationDispatcherMockRecorder {
	return m.recorder
}

// TriggerDispatch mocks base method.
func (m *MockKdsNotificationDispatcher) TriggerDispatch() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerDispatch")
}

// TriggerDispatch indicates an expected call of TriggerDispatch.
func (mr *MockKdsNotificationDispatcherMockRecorder) TriggerDispatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerDispatch", reflect.TypeOf((*MockKdsNotificationDispatcher)(nil).TriggerDispatch))
}
