// Code generated by MockGen. DO NOT EDIT.
// Source: kds_device_repository.go
//
// Generated by this command:
//
//	mockgen -source=kds_device_repository.go -destination=../data/mock/kds_device_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKdsDeviceRepository is a mock of KdsDeviceRepository interface.
type MockKdsDeviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKdsDeviceRepositoryMockRecorder
	isgomock struct{}
}

// MockKdsDeviceRepositoryMockRecorder is the mock recorder for MockKdsDeviceRepository.
type MockKdsDeviceRepositoryMockRecorder struct {
	mock *MockKdsDeviceRepository
}

// NewMockKdsDeviceRepository creates a new mock instance.
func NewMockKdsDeviceRepository(ctrl *gomock.Controller) *MockKdsDeviceRepository {
	mock := &MockKdsDeviceRepository{ctrl: ctrl}
	mock.recorder = &MockKdsDeviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKdsDeviceRepository) EXPECT() *MockKdsDeviceRepositoryMockRecorder {
	return m.recorder
}

// DeleteKdsDeviceById mocks base method.
func (m *MockKdsDeviceRepository) DeleteKdsDeviceById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKdsDeviceById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteKdsDeviceById indicates an expected call of DeleteKdsDeviceById.
func (mr *MockKdsDeviceRepositoryMockRecorder) DeleteKdsDeviceById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKdsDeviceById", reflect.TypeOf((*MockKdsDeviceRepository)(nil).DeleteKdsDeviceById), ctx, id)
}

// GetKdsDeviceById mocks base method.
func (m *MockKdsDeviceRepository) GetKdsDeviceById(ctx context.Context, id int64) (domain.KdsDevice, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKdsDeviceById", ctx, id)
	ret0, _ := ret[0].(domain.KdsDevice)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetKdsDeviceById indicates an expected call of GetKdsDeviceById.
func (mr *MockKdsDeviceRepositoryMockRecorder) GetKdsDeviceById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKdsDeviceById", reflect.TypeOf((*MockKdsDeviceRepository)(nil).GetKdsDeviceById), ctx, id)
}

// GetKdsDeviceList mocks base method.
func (m *MockKdsDeviceRepository) GetKdsDeviceList(ctx context.Context) ([]domain.KdsDevice, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKdsDeviceList", ctx)
	ret0, _ := ret[0].([]domain.KdsDevice)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetKdsDeviceList indicates an expected call of GetKdsDeviceList.
func (mr *MockKdsDeviceRepositoryMockRecorder) GetKdsDeviceList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKdsDeviceList", reflect.TypeOf((*MockKdsDeviceRepository)(nil).GetKdsDeviceList), ctx)
}

// RegisterKdsDevice mocks base method.
func (m *MockKdsDeviceRepository) RegisterKdsDevice(ctx context.Context, device domain.KdsDevice) (domain.KdsDevice, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterKdsDevice", ctx, device)
	ret0, _ := ret[0].(domain.KdsDevice)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// RegisterKdsDevice indicates an expected call of RegisterKdsDevice.
func (mr *MockKdsDeviceRepositoryMockRecorder) RegisterKdsDevice(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterKdsDevice", reflect.TypeOf((*MockKdsDeviceRepository)(nil).RegisterKdsDevice), ctx, device)
}
