// Code generated by MockGen. DO NOT EDIT.
// Source: kds_notification_repository.go
//
// Generated by this command:
//
//	mockgen -source=kds_notification_repository.go -destination=../data/mock/kds_notification_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKdsPushGatewayRepository is a mock of KdsPushGatewayRepository interface.
type MockKdsPushGatewayRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKdsPushGatewayRepositoryMockRecorder
	isgomock struct{}
}

// MockKdsPushGatewayRepositoryMockRecorder is the mock recorder for MockKdsPushGatewayRepository.
type MockKdsPushGatewayRepositoryMockRecorder struct {
	mock *MockKdsPushGatewayRepository
}

// NewMockKdsPushGatewayRepository creates a new mock instance.
func NewMockKdsPushGatewayRepository(ctrl *gomock.Controller) *MockKdsPushGatewayRepository {
	mock := &MockKdsPushGatewayRepository{ctrl: ctrl}
	mock.recorder = &MockKdsPushGatewayRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKdsPushGatewayRepository) EXPECT() *MockKdsPushGatewayRepositoryMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockKdsPushGatewayRepository) Send(ctx context.Context, messages []domain.KdsPushMessage) ([]domain.KdsPushReceipt, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, messages)
	ret0, _ := ret[0].([]domain.KdsPushReceipt)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockKdsPushGatewayRepositoryMockRecorder) Send(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockKdsPushGatewayRepository)(nil).Send), ctx, messages)
}
