// Code generated by MockGen. DO NOT EDIT.
// Source: material_repository.go
//
// Generated by this command:
//
//	mockgen -source=material_repository.go -destination=../data/mock/material_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMaterialRepository is a mock of MaterialRepository interface.
type MockMaterialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMaterialRepositoryMockRecorder
	isgomock struct{}
}

// MockMaterialRepositoryMockRecorder is the mock recorder for MockMaterialRepository.
type MockMaterialRepositoryMockRecorder struct {
	mock *MockMaterialRepository
}

// NewMockMaterialRepository creates a new mock instance.
func NewMockMaterialRepository(ctrl *gomock.Controller) *MockMaterialRepository {
	mock := &MockMaterialRepository{ctrl: ctrl}
	mock.recorder = &MockMaterialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaterialRepository) EXPECT() *MockMaterialRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockMaterialRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockMaterialRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockMaterialRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateMaterial mocks base method.
func (m *MockMaterialRepository) CreateMaterial(ctx context.Context, material domain.Material) (domain.Material, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMaterial", ctx, material)
	ret0, _ := ret[0].(domain.Material)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateMaterial indicates an expected call of CreateMaterial.
func (mr *MockMaterialRepositoryMockRecorder) CreateMaterial(ctx, material any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMaterial", reflect.TypeOf((*MockMaterialRepository)(nil).CreateMaterial), ctx, material)
}

// DeleteMaterialById mocks base method.
func (m *MockMaterialRepository) DeleteMaterialById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMaterialById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteMaterialById indicates an expected call of DeleteMaterialById.
func (mr *MockMaterialRepositoryMockRecorder) DeleteMaterialById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMaterialById", reflect.TypeOf((*MockMaterialRepository)(nil).DeleteMaterialById), ctx, id)
}

// GetMaterialById mocks base method.
func (m *MockMaterialRepository) GetMaterialById(ctx context.Context, id int64) (domain.Material, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterialById", ctx, id)
	ret0, _ := ret[0].(domain.Material)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetMaterialById indicates an expected call of GetMaterialById.
func (mr *MockMaterialRepositoryMockRecorder) GetMaterialById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterialById", reflect.TypeOf((*MockMaterialRepository)(nil).GetMaterialById), ctx, id)
}

// GetMaterialList mocks base method.
func (m *MockMaterialRepository) GetMaterialList(ctx context.Context, query string, sortBy domain.SortBy, order domain.Order, skip, limit int) ([]domain.Material, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterialList", ctx, query, sortBy, order, skip, limit)
	ret0, _ := ret[0].([]domain.Material)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetMaterialList indicates an expected call of GetMaterialList.
func (mr *MockMaterialRepositoryMockRecorder) GetMaterialList(ctx, query, sortBy, order, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterialList", reflect.TypeOf((*MockMaterialRepository)(nil).GetMaterialList), ctx, query, sortBy, order, skip, limit)
}

// GetMaterialListTotal mocks base method.
func (m *MockMaterialRepository) GetMaterialListTotal(ctx context.Context, query string) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterialListTotal", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetMaterialListTotal indicates an expected call of GetMaterialListTotal.
func (mr *MockMaterialRepositoryMockRecorder) GetMaterialListTotal(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterialListTotal", reflect.TypeOf((*MockMaterialRepository)(nil).GetMaterialListTotal), ctx, query)
}

// GetMaterialsWeeklyUsage mocks base method.
func (m *MockMaterialRepository) GetMaterialsWeeklyUsage(ctx context.Context, ids []int64) (map[int64]float32, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaterialsWeeklyUsage", ctx, ids)
	ret0, _ := ret[0].(map[int64]float32)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetMaterialsWeeklyUsage indicates an expected call of GetMaterialsWeeklyUsage.
func (mr *MockMaterialRepositoryMockRecorder) GetMaterialsWeeklyUsage(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaterialsWeeklyUsage", reflect.TypeOf((*MockMaterialRepository)(nil).GetMaterialsWeeklyUsage), ctx, ids)
}

// UpdateMaterialById mocks base method.
func (m *MockMaterialRepository) UpdateMaterialById(ctx context.Context, material domain.Material, id int64) (domain.Material, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaterialById", ctx, material, id)
	ret0, _ := ret[0].(domain.Material)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateMaterialById indicates an expected call of UpdateMaterialById.
func (mr *MockMaterialRepositoryMockRecorder) UpdateMaterialById(ctx, material, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaterialById", reflect.TypeOf((*MockMaterialRepository)(nil).UpdateMaterialById), ctx, material, id)
}
