// Code generated by MockGen. DO NOT EDIT.
// Source: payment_repository.go
//
// Generated by this command:
//
//	mockgen -source=payment_repository.go -destination=../data/mock/payment_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentGatewayRepository is a mock of PaymentGatewayRepository interface.
type MockPaymentGatewayRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentGatewayRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentGatewayRepositoryMockRecorder is the mock recorder for MockPaymentGatewayRepository.
type MockPaymentGatewayRepositoryMockRecorder struct {
	mock *MockPaymentGatewayRepository
}

// NewMockPaymentGatewayRepository creates a new mock instance.
func NewMockPaymentGatewayRepository(ctrl *gomock.Controller) *MockPaymentGatewayRepository {
	mock := &MockPaymentGatewayRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentGatewayRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentGatewayRepository) EXPECT() *MockPaymentGatewayRepositoryMockRecorder {
	return m.recorder
}

// GenerateQris mocks base method.
func (m *MockPaymentGatewayRepository) GenerateQris(ctx context.Context, input domain.GenerateQrisInput) (domain.QrisPayment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateQris", ctx, input)
	ret0, _ := ret[0].(domain.QrisPayment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GenerateQris indicates an expected call of GenerateQris.
func (mr *MockPaymentGatewayRepositoryMockRecorder) GenerateQris(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateQris", reflect.TypeOf((*MockPaymentGatewayRepository)(nil).GenerateQris), ctx, input)
}

// ParseNotification mocks base method.
func (m *MockPaymentGatewayRepository) ParseNotification(body []byte) (domain.QrisStatus, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseNotification", body)
	ret0, _ := ret[0].(domain.QrisStatus)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// ParseNotification indicates an expected call of ParseNotification.
func (mr *MockPaymentGatewayRepositoryMockRecorder) ParseNotification(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseNotification", reflect.TypeOf((*MockPaymentGatewayRepository)(nil).ParseNotification), body)
}

// QueryQris mocks base method.
func (m *MockPaymentGatewayRepository) QueryQris(ctx context.Context, input domain.QueryQrisInput) (domain.QrisStatus, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryQris", ctx, input)
	ret0, _ := ret[0].(domain.QrisStatus)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// QueryQris indicates an expected call of QueryQris.
func (mr *MockPaymentGatewayRepositoryMockRecorder) QueryQris(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryQris", reflect.TypeOf((*MockPaymentGatewayRepository)(nil).QueryQris), ctx, input)
}

// VerifyNotificationSignature mocks base method.
func (m *MockPaymentGatewayRepository) VerifyNotificationSignature(method, path string, headers domain.NotificationHeaders, body []byte) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyNotificationSignature", method, path, headers, body)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// VerifyNotificationSignature indicates an expected call of VerifyNotificationSignature.
func (mr *MockPaymentGatewayRepositoryMockRecorder) VerifyNotificationSignature(method, path, headers, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyNotificationSignature", reflect.TypeOf((*MockPaymentGatewayRepository)(nil).VerifyNotificationSignature), method, path, headers, body)
}
