// Code generated by MockGen. DO NOT EDIT.
// Source: payment_repository.go
//
// Generated by this command:
//
//	mockgen -source=payment_repository.go -destination=../data/mock/payment_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockPaymentRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockPaymentRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockPaymentRepository)(nil).BeginTransaction), ctx, callback)
}

// CreatePayment mocks base method.
func (m *MockPaymentRepository) CreatePayment(ctx context.Context, payment domain.Payment) (domain.Payment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, payment)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentRepositoryMockRecorder) CreatePayment(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentRepository)(nil).CreatePayment), ctx, payment)
}

// GetExpirablePayments mocks base method.
func (m *MockPaymentRepository) GetExpirablePayments(ctx context.Context, now time.Time, limit int) ([]domain.Payment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpirablePayments", ctx, now, limit)
	ret0, _ := ret[0].([]domain.Payment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetExpirablePayments indicates an expected call of GetExpirablePayments.
func (mr *MockPaymentRepositoryMockRecorder) GetExpirablePayments(ctx, now, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpirablePayments", reflect.TypeOf((*MockPaymentRepository)(nil).GetExpirablePayments), ctx, now, limit)
}

// GetPaymentByPartnerReferenceNo mocks base method.
func (m *MockPaymentRepository) GetPaymentByPartnerReferenceNo(ctx context.Context, partnerReferenceNo string) (domain.Payment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByPartnerReferenceNo", ctx, partnerReferenceNo)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetPaymentByPartnerReferenceNo indicates an expected call of GetPaymentByPartnerReferenceNo.
func (mr *MockPaymentRepositoryMockRecorder) GetPaymentByPartnerReferenceNo(ctx, partnerReferenceNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByPartnerReferenceNo", reflect.TypeOf((*MockPaymentRepository)(nil).GetPaymentByPartnerReferenceNo), ctx, partnerReferenceNo)
}

// GetPaymentByPartnerReferenceNoForUpdate mocks base method.
func (m *MockPaymentRepository) GetPaymentByPartnerReferenceNoForUpdate(ctx context.Context, partnerReferenceNo string) (domain.Payment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByPartnerReferenceNoForUpdate", ctx, partnerReferenceNo)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetPaymentByPartnerReferenceNoForUpdate indicates an expected call of GetPaymentByPartnerReferenceNoForUpdate.
func (mr *MockPaymentRepositoryMockRecorder) GetPaymentByPartnerReferenceNoForUpdate(ctx, partnerReferenceNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByPartnerReferenceNoForUpdate", reflect.TypeOf((*MockPaymentRepository)(nil).GetPaymentByPartnerReferenceNoForUpdate), ctx, partnerReferenceNo)
}

// GetPaymentByTransactionId mocks base method.
func (m *MockPaymentRepository) GetPaymentByTransactionId(ctx context.Context, transactionId int64) (domain.Payment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByTransactionId", ctx, transactionId)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetPaymentByTransactionId indicates an expected call of GetPaymentByTransactionId.
func (mr *MockPaymentRepositoryMockRecorder) GetPaymentByTransactionId(ctx, transactionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByTransactionId", reflect.TypeOf((*MockPaymentRepository)(nil).GetPaymentByTransactionId), ctx, transactionId)
}

// GetPaymentByTransactionIdForUpdate mocks base method.
func (m *MockPaymentRepository) GetPaymentByTransactionIdForUpdate(ctx context.Context, transactionId int64) (domain.Payment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByTransactionIdForUpdate", ctx, transactionId)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetPaymentByTransactionIdForUpdate indicates an expected call of GetPaymentByTransactionIdForUpdate.
func (mr *MockPaymentRepositoryMockRecorder) GetPaymentByTransactionIdForUpdate(ctx, transactionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByTransactionIdForUpdate", reflect.TypeOf((*MockPaymentRepository)(nil).GetPaymentByTransactionIdForUpdate), ctx, transactionId)
}

// GetPaymentsBySessionId mocks base method.
func (m *MockPaymentRepository) GetPaymentsBySessionId(ctx context.Context, sessionId string, skip, limit int) ([]domain.Payment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentsBySessionId", ctx, sessionId, skip, limit)
	ret0, _ := ret[0].([]domain.Payment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetPaymentsBySessionId indicates an expected call of GetPaymentsBySessionId.
func (mr *MockPaymentRepositoryMockRecorder) GetPaymentsBySessionId(ctx, sessionId, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentsBySessionId", reflect.TypeOf((*MockPaymentRepository)(nil).GetPaymentsBySessionId), ctx, sessionId, skip, limit)
}

// GetPaymentsBySessionIdTotal mocks base method.
func (m *MockPaymentRepository) GetPaymentsBySessionIdTotal(ctx context.Context, sessionId string) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentsBySessionIdTotal", ctx, sessionId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetPaymentsBySessionIdTotal indicates an expected call of GetPaymentsBySessionIdTotal.
func (mr *MockPaymentRepositoryMockRecorder) GetPaymentsBySessionIdTotal(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentsBySessionIdTotal", reflect.TypeOf((*MockPaymentRepository)(nil).GetPaymentsBySessionIdTotal), ctx, sessionId)
}

// GetPendingPaymentByCartId mocks base method.
func (m *MockPaymentRepository) GetPendingPaymentByCartId(ctx context.Context, cartId int64) (domain.Payment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingPaymentByCartId", ctx, cartId)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetPendingPaymentByCartId indicates an expected call of GetPendingPaymentByCartId.
func (mr *MockPaymentRepositoryMockRecorder) GetPendingPaymentByCartId(ctx, cartId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingPaymentByCartId", reflect.TypeOf((*MockPaymentRepository)(nil).GetPendingPaymentByCartId), ctx, cartId)
}

// UpdatePaymentById mocks base method.
func (m *MockPaymentRepository) UpdatePaymentById(ctx context.Context, payment domain.Payment, id int64) (domain.Payment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentById", ctx, payment, id)
	ret0, _ := ret[0].(domain.Payment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdatePaymentById indicates an expected call of UpdatePaymentById.
func (mr *MockPaymentRepositoryMockRecorder) UpdatePaymentById(ctx, payment, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentById", reflect.TypeOf((*MockPaymentRepository)(nil).UpdatePaymentById), ctx, payment, id)
}

// MockPaymentGatewayRepository is a mock of PaymentGatewayRepository interface.
type MockPaymentGatewayRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentGatewayRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentGatewayRepositoryMockRecorder is the mock recorder for MockPaymentGatewayRepository.
type MockPaymentGatewayRepositoryMockRecorder struct {
	mock *MockPaymentGatewayRepository
}

// NewMockPaymentGatewayRepository creates a new mock instance.
func NewMockPaymentGatewayRepository(ctrl *gomock.Controller) *MockPaymentGatewayRepository {
	mock := &MockPaymentGatewayRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentGatewayRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentGatewayRepository) EXPECT() *MockPaymentGatewayRepositoryMockRecorder {
	return m.recorder
}

// GenerateQris mocks base method.
func (m *MockPaymentGatewayRepository) GenerateQris(ctx context.Context, input domain.GenerateQrisInput) (domain.QrisPayment, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateQris", ctx, input)
	ret0, _ := ret[0].(domain.QrisPayment)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GenerateQris indicates an expected call of GenerateQris.
func (mr *MockPaymentGatewayRepositoryMockRecorder) GenerateQris(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateQris", reflect.TypeOf((*MockPaymentGatewayRepository)(nil).GenerateQris), ctx, input)
}

// QueryQris mocks base method.
func (m *MockPaymentGatewayRepository) QueryQris(ctx context.Context, input domain.QueryQrisInput) (domain.QrisStatus, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryQris", ctx, input)
	ret0, _ := ret[0].(domain.QrisStatus)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// QueryQris indicates an expected call of QueryQris.
func (mr *MockPaymentGatewayRepositoryMockRecorder) QueryQris(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryQris", reflect.TypeOf((*MockPaymentGatewayRepository)(nil).QueryQris), ctx, input)
}
