// Code generated by MockGen. DO NOT EDIT.
// Source: payment_verification_repository.go
//
// Generated by this command:
//
//	mockgen -source=payment_verification_repository.go -destination=../data/mock/payment_verification_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentVerificationRepository is a mock of PaymentVerificationRepository interface.
type MockPaymentVerificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentVerificationRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentVerificationRepositoryMockRecorder is the mock recorder for MockPaymentVerificationRepository.
type MockPaymentVerificationRepositoryMockRecorder struct {
	mock *MockPaymentVerificationRepository
}

// NewMockPaymentVerificationRepository creates a new mock instance.
func NewMockPaymentVerificationRepository(ctrl *gomock.Controller) *MockPaymentVerificationRepository {
	mock := &MockPaymentVerificationRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentVerificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentVerificationRepository) EXPECT() *MockPaymentVerificationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentVerificationRepository) Create(ctx context.Context, photo domain.PaymentVerificationPhoto) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, photo)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentVerificationRepositoryMockRecorder) Create(ctx, photo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentVerificationRepository)(nil).Create), ctx, photo)
}

// DeleteByPaymentId mocks base method.
func (m *MockPaymentVerificationRepository) DeleteByPaymentId(ctx context.Context, paymentId int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPaymentId", ctx, paymentId)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteByPaymentId indicates an expected call of DeleteByPaymentId.
func (mr *MockPaymentVerificationRepositoryMockRecorder) DeleteByPaymentId(ctx, paymentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPaymentId", reflect.TypeOf((*MockPaymentVerificationRepository)(nil).DeleteByPaymentId), ctx, paymentId)
}

// DeleteOrphaned mocks base method.
func (m *MockPaymentVerificationRepository) DeleteOrphaned(ctx context.Context, limit int) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrphaned", ctx, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// DeleteOrphaned indicates an expected call of DeleteOrphaned.
func (mr *MockPaymentVerificationRepositoryMockRecorder) DeleteOrphaned(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrphaned", reflect.TypeOf((*MockPaymentVerificationRepository)(nil).DeleteOrphaned), ctx, limit)
}

// GetByPaymentId mocks base method.
func (m *MockPaymentVerificationRepository) GetByPaymentId(ctx context.Context, paymentId int64) (domain.PaymentVerificationPhoto, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPaymentId", ctx, paymentId)
	ret0, _ := ret[0].(domain.PaymentVerificationPhoto)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetByPaymentId indicates an expected call of GetByPaymentId.
func (mr *MockPaymentVerificationRepositoryMockRecorder) GetByPaymentId(ctx, paymentId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPaymentId", reflect.TypeOf((*MockPaymentVerificationRepository)(nil).GetByPaymentId), ctx, paymentId)
}
