// Code generated by MockGen. DO NOT EDIT.
// Source: pricing_tier_repository.go
//
// Generated by this command:
//
//	mockgen -source=pricing_tier_repository.go -destination=../data/mock/pricing_tier_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPricingTierRepository is a mock of PricingTierRepository interface.
type MockPricingTierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPricingTierRepositoryMockRecorder
	isgomock struct{}
}

// MockPricingTierRepositoryMockRecorder is the mock recorder for MockPricingTierRepository.
type MockPricingTierRepositoryMockRecorder struct {
	mock *MockPricingTierRepository
}

// NewMockPricingTierRepository creates a new mock instance.
func NewMockPricingTierRepository(ctrl *gomock.Controller) *MockPricingTierRepository {
	mock := &MockPricingTierRepository{ctrl: ctrl}
	mock.recorder = &MockPricingTierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricingTierRepository) EXPECT() *MockPricingTierRepositoryMockRecorder {
	return m.recorder
}

// GetTiersByVariantId mocks base method.
func (m *MockPricingTierRepository) GetTiersByVariantId(ctx context.Context, variantId int64) ([]domain.PricingTier, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTiersByVariantId", ctx, variantId)
	ret0, _ := ret[0].([]domain.PricingTier)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTiersByVariantId indicates an expected call of GetTiersByVariantId.
func (mr *MockPricingTierRepositoryMockRecorder) GetTiersByVariantId(ctx, variantId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTiersByVariantId", reflect.TypeOf((*MockPricingTierRepository)(nil).GetTiersByVariantId), ctx, variantId)
}

// ReplaceTiersForVariant mocks base method.
func (m *MockPricingTierRepository) ReplaceTiersForVariant(ctx context.Context, variantId int64, tiers []domain.PricingTier) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTiersForVariant", ctx, variantId, tiers)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// ReplaceTiersForVariant indicates an expected call of ReplaceTiersForVariant.
func (mr *MockPricingTierRepositoryMockRecorder) ReplaceTiersForVariant(ctx, variantId, tiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTiersForVariant", reflect.TypeOf((*MockPricingTierRepository)(nil).ReplaceTiersForVariant), ctx, variantId, tiers)
}
