// Code generated by MockGen. DO NOT EDIT.
// Source: product_repository.go
//
// Generated by this command:
//
//	mockgen -source=product_repository.go -destination=../data/mock/product_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockProductRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockProductRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockProductRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateProduct mocks base method.
func (m *MockProductRepository) CreateProduct(ctx context.Context, product domain.Product) (domain.Product, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, product)
	ret0, _ := ret[0].(domain.Product)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductRepositoryMockRecorder) CreateProduct(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductRepository)(nil).CreateProduct), ctx, product)
}

// DeleteProductById mocks base method.
func (m *MockProductRepository) DeleteProductById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteProductById indicates an expected call of DeleteProductById.
func (mr *MockProductRepositoryMockRecorder) DeleteProductById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductById", reflect.TypeOf((*MockProductRepository)(nil).DeleteProductById), ctx, id)
}

// GetProductById mocks base method.
func (m *MockProductRepository) GetProductById(ctx context.Context, id int64) (domain.Product, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductById", ctx, id)
	ret0, _ := ret[0].(domain.Product)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetProductById indicates an expected call of GetProductById.
func (mr *MockProductRepositoryMockRecorder) GetProductById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductById", reflect.TypeOf((*MockProductRepository)(nil).GetProductById), ctx, id)
}

// GetProductList mocks base method.
func (m *MockProductRepository) GetProductList(ctx context.Context, query string, sortBy domain.SortBy, order domain.Order, skip, limit int, saleType *domain.SaleType) ([]domain.Product, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductList", ctx, query, sortBy, order, skip, limit, saleType)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetProductList indicates an expected call of GetProductList.
func (mr *MockProductRepositoryMockRecorder) GetProductList(ctx, query, sortBy, order, skip, limit, saleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductList", reflect.TypeOf((*MockProductRepository)(nil).GetProductList), ctx, query, sortBy, order, skip, limit, saleType)
}

// GetProductListTotal mocks base method.
func (m *MockProductRepository) GetProductListTotal(ctx context.Context, query string, saleType *domain.SaleType) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductListTotal", ctx, query, saleType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetProductListTotal indicates an expected call of GetProductListTotal.
func (mr *MockProductRepositoryMockRecorder) GetProductListTotal(ctx, query, saleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductListTotal", reflect.TypeOf((*MockProductRepository)(nil).GetProductListTotal), ctx, query, saleType)
}

// UpdateProductById mocks base method.
func (m *MockProductRepository) UpdateProductById(ctx context.Context, product domain.Product, id int64) (domain.Product, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductById", ctx, product, id)
	ret0, _ := ret[0].(domain.Product)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateProductById indicates an expected call of UpdateProductById.
func (mr *MockProductRepositoryMockRecorder) UpdateProductById(ctx, product, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductById", reflect.TypeOf((*MockProductRepository)(nil).UpdateProductById), ctx, product, id)
}
