// Code generated by MockGen. DO NOT EDIT.
// Source: rental_repository.go
//
// Generated by this command:
//
//	mockgen -source=rental_repository.go -destination=../data/mock/rental_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRentalRepository is a mock of RentalRepository interface.
type MockRentalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRentalRepositoryMockRecorder
	isgomock struct{}
}

// MockRentalRepositoryMockRecorder is the mock recorder for MockRentalRepository.
type MockRentalRepositoryMockRecorder struct {
	mock *MockRentalRepository
}

// NewMockRentalRepository creates a new mock instance.
func NewMockRentalRepository(ctrl *gomock.Controller) *MockRentalRepository {
	mock := &MockRentalRepository{ctrl: ctrl}
	mock.recorder = &MockRentalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRentalRepository) EXPECT() *MockRentalRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockRentalRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockRentalRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockRentalRepository)(nil).BeginTransaction), ctx, callback)
}

// CheckinRentals mocks base method.
func (m *MockRentalRepository) CheckinRentals(ctx context.Context, rentals []domain.Rental) ([]domain.Rental, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckinRentals", ctx, rentals)
	ret0, _ := ret[0].([]domain.Rental)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CheckinRentals indicates an expected call of CheckinRentals.
func (mr *MockRentalRepositoryMockRecorder) CheckinRentals(ctx, rentals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckinRentals", reflect.TypeOf((*MockRentalRepository)(nil).CheckinRentals), ctx, rentals)
}

// CheckoutRental mocks base method.
func (m *MockRentalRepository) CheckoutRental(ctx context.Context, rentalId int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutRental", ctx, rentalId)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// CheckoutRental indicates an expected call of CheckoutRental.
func (mr *MockRentalRepositoryMockRecorder) CheckoutRental(ctx, rentalId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutRental", reflect.TypeOf((*MockRentalRepository)(nil).CheckoutRental), ctx, rentalId)
}

// DeleteRentalById mocks base method.
func (m *MockRentalRepository) DeleteRentalById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRentalById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteRentalById indicates an expected call of DeleteRentalById.
func (mr *MockRentalRepositoryMockRecorder) DeleteRentalById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRentalById", reflect.TypeOf((*MockRentalRepository)(nil).DeleteRentalById), ctx, id)
}

// GetRentalById mocks base method.
func (m *MockRentalRepository) GetRentalById(ctx context.Context, id int64) (domain.Rental, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRentalById", ctx, id)
	ret0, _ := ret[0].(domain.Rental)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetRentalById indicates an expected call of GetRentalById.
func (mr *MockRentalRepositoryMockRecorder) GetRentalById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRentalById", reflect.TypeOf((*MockRentalRepository)(nil).GetRentalById), ctx, id)
}

// GetRentalList mocks base method.
func (m *MockRentalRepository) GetRentalList(ctx context.Context, query string, sortBy domain.SortBy, order domain.Order, skip, limit int, checkoutStatus domain.CheckoutStatus) ([]domain.Rental, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRentalList", ctx, query, sortBy, order, skip, limit, checkoutStatus)
	ret0, _ := ret[0].([]domain.Rental)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetRentalList indicates an expected call of GetRentalList.
func (mr *MockRentalRepositoryMockRecorder) GetRentalList(ctx, query, sortBy, order, skip, limit, checkoutStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRentalList", reflect.TypeOf((*MockRentalRepository)(nil).GetRentalList), ctx, query, sortBy, order, skip, limit, checkoutStatus)
}

// GetRentalListTotal mocks base method.
func (m *MockRentalRepository) GetRentalListTotal(ctx context.Context, query string, checkoutStatus domain.CheckoutStatus) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRentalListTotal", ctx, query, checkoutStatus)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetRentalListTotal indicates an expected call of GetRentalListTotal.
func (mr *MockRentalRepositoryMockRecorder) GetRentalListTotal(ctx, query, checkoutStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRentalListTotal", reflect.TypeOf((*MockRentalRepository)(nil).GetRentalListTotal), ctx, query, checkoutStatus)
}
