// Code generated by MockGen. DO NOT EDIT.
// Source: stock_check_repository.go

package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStockCheckRepository is a mock of StockCheckRepository interface.
type MockStockCheckRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStockCheckRepositoryMockRecorder
	isgomock struct{}
}

// MockStockCheckRepositoryMockRecorder is the mock recorder for MockStockCheckRepository.
type MockStockCheckRepositoryMockRecorder struct {
	mock *MockStockCheckRepository
}

// NewMockStockCheckRepository creates a new mock instance.
func NewMockStockCheckRepository(ctrl *gomock.Controller) *MockStockCheckRepository {
	mock := &MockStockCheckRepository{ctrl: ctrl}
	mock.recorder = &MockStockCheckRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockCheckRepository) EXPECT() *MockStockCheckRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockStockCheckRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockStockCheckRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockStockCheckRepository)(nil).BeginTransaction), ctx, callback)
}

// GetStockCheckList mocks base method.
func (m *MockStockCheckRepository) GetStockCheckList(ctx context.Context, sortBy domain.SortBy, order domain.Order, skip, limit int) ([]domain.StockCheck, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockCheckList", ctx, sortBy, order, skip, limit)
	ret0, _ := ret[0].([]domain.StockCheck)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetStockCheckList indicates an expected call of GetStockCheckList.
func (mr *MockStockCheckRepositoryMockRecorder) GetStockCheckList(ctx, sortBy, order, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockCheckList", reflect.TypeOf((*MockStockCheckRepository)(nil).GetStockCheckList), ctx, sortBy, order, skip, limit)
}

// GetStockCheckListTotal mocks base method.
func (m *MockStockCheckRepository) GetStockCheckListTotal(ctx context.Context) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockCheckListTotal", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetStockCheckListTotal indicates an expected call of GetStockCheckListTotal.
func (mr *MockStockCheckRepositoryMockRecorder) GetStockCheckListTotal(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockCheckListTotal", reflect.TypeOf((*MockStockCheckRepository)(nil).GetStockCheckListTotal), ctx)
}

// GetStockCheckById mocks base method.
func (m *MockStockCheckRepository) GetStockCheckById(ctx context.Context, id int64) (domain.StockCheck, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockCheckById", ctx, id)
	ret0, _ := ret[0].(domain.StockCheck)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetStockCheckById indicates an expected call of GetStockCheckById.
func (mr *MockStockCheckRepositoryMockRecorder) GetStockCheckById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockCheckById", reflect.TypeOf((*MockStockCheckRepository)(nil).GetStockCheckById), ctx, id)
}

// GetStockCheckByDate mocks base method.
func (m *MockStockCheckRepository) GetStockCheckByDate(ctx context.Context, checkDate string) (domain.StockCheck, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockCheckByDate", ctx, checkDate)
	ret0, _ := ret[0].(domain.StockCheck)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetStockCheckByDate indicates an expected call of GetStockCheckByDate.
func (mr *MockStockCheckRepositoryMockRecorder) GetStockCheckByDate(ctx, checkDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockCheckByDate", reflect.TypeOf((*MockStockCheckRepository)(nil).GetStockCheckByDate), ctx, checkDate)
}

// CreateStockCheck mocks base method.
func (m *MockStockCheckRepository) CreateStockCheck(ctx context.Context, stockCheck domain.StockCheck) (domain.StockCheck, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStockCheck", ctx, stockCheck)
	ret0, _ := ret[0].(domain.StockCheck)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateStockCheck indicates an expected call of CreateStockCheck.
func (mr *MockStockCheckRepositoryMockRecorder) CreateStockCheck(ctx, stockCheck any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStockCheck", reflect.TypeOf((*MockStockCheckRepository)(nil).CreateStockCheck), ctx, stockCheck)
}

// UpdateStockCheckById mocks base method.
func (m *MockStockCheckRepository) UpdateStockCheckById(ctx context.Context, stockCheck domain.StockCheck, id int64) (domain.StockCheck, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStockCheckById", ctx, stockCheck, id)
	ret0, _ := ret[0].(domain.StockCheck)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateStockCheckById indicates an expected call of UpdateStockCheckById.
func (mr *MockStockCheckRepositoryMockRecorder) UpdateStockCheckById(ctx, stockCheck, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStockCheckById", reflect.TypeOf((*MockStockCheckRepository)(nil).UpdateStockCheckById), ctx, stockCheck, id)
}

// DeleteStockCheckById mocks base method.
func (m *MockStockCheckRepository) DeleteStockCheckById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStockCheckById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteStockCheckById indicates an expected call of DeleteStockCheckById.
func (mr *MockStockCheckRepositoryMockRecorder) DeleteStockCheckById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStockCheckById", reflect.TypeOf((*MockStockCheckRepository)(nil).DeleteStockCheckById), ctx, id)
}
