// Code generated by MockGen. DO NOT EDIT.
// Source: supplier_repository.go
//
// Generated by this command:
//
//	mockgen -source=supplier_repository.go -destination=../data/mock/supplier_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSupplierRepository is a mock of SupplierRepository interface.
type MockSupplierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSupplierRepositoryMockRecorder
	isgomock struct{}
}

// MockSupplierRepositoryMockRecorder is the mock recorder for MockSupplierRepository.
type MockSupplierRepositoryMockRecorder struct {
	mock *MockSupplierRepository
}

// NewMockSupplierRepository creates a new mock instance.
func NewMockSupplierRepository(ctrl *gomock.Controller) *MockSupplierRepository {
	mock := &MockSupplierRepository{ctrl: ctrl}
	mock.recorder = &MockSupplierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupplierRepository) EXPECT() *MockSupplierRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockSupplierRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockSupplierRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockSupplierRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateSupplier mocks base method.
func (m *MockSupplierRepository) CreateSupplier(ctx context.Context, supplier domain.Supplier) (domain.Supplier, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSupplier", ctx, supplier)
	ret0, _ := ret[0].(domain.Supplier)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateSupplier indicates an expected call of CreateSupplier.
func (mr *MockSupplierRepositoryMockRecorder) CreateSupplier(ctx, supplier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSupplier", reflect.TypeOf((*MockSupplierRepository)(nil).CreateSupplier), ctx, supplier)
}

// DeleteSupplierById mocks base method.
func (m *MockSupplierRepository) DeleteSupplierById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupplierById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteSupplierById indicates an expected call of DeleteSupplierById.
func (mr *MockSupplierRepositoryMockRecorder) DeleteSupplierById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupplierById", reflect.TypeOf((*MockSupplierRepository)(nil).DeleteSupplierById), ctx, id)
}

// GetSupplierById mocks base method.
func (m *MockSupplierRepository) GetSupplierById(ctx context.Context, id int64) (domain.Supplier, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplierById", ctx, id)
	ret0, _ := ret[0].(domain.Supplier)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetSupplierById indicates an expected call of GetSupplierById.
func (mr *MockSupplierRepositoryMockRecorder) GetSupplierById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplierById", reflect.TypeOf((*MockSupplierRepository)(nil).GetSupplierById), ctx, id)
}

// GetSupplierList mocks base method.
func (m *MockSupplierRepository) GetSupplierList(ctx context.Context, query string, sortBy domain.SortBy, order domain.Order, skip, limit int) ([]domain.Supplier, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplierList", ctx, query, sortBy, order, skip, limit)
	ret0, _ := ret[0].([]domain.Supplier)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetSupplierList indicates an expected call of GetSupplierList.
func (mr *MockSupplierRepositoryMockRecorder) GetSupplierList(ctx, query, sortBy, order, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplierList", reflect.TypeOf((*MockSupplierRepository)(nil).GetSupplierList), ctx, query, sortBy, order, skip, limit)
}

// GetSupplierListTotal mocks base method.
func (m *MockSupplierRepository) GetSupplierListTotal(ctx context.Context, query string) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplierListTotal", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetSupplierListTotal indicates an expected call of GetSupplierListTotal.
func (mr *MockSupplierRepositoryMockRecorder) GetSupplierListTotal(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplierListTotal", reflect.TypeOf((*MockSupplierRepository)(nil).GetSupplierListTotal), ctx, query)
}

// UpdateSupplierById mocks base method.
func (m *MockSupplierRepository) UpdateSupplierById(ctx context.Context, supplier domain.Supplier, id int64) (domain.Supplier, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSupplierById", ctx, supplier, id)
	ret0, _ := ret[0].(domain.Supplier)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateSupplierById indicates an expected call of UpdateSupplierById.
func (mr *MockSupplierRepositoryMockRecorder) UpdateSupplierById(ctx, supplier, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSupplierById", reflect.TypeOf((*MockSupplierRepository)(nil).UpdateSupplierById), ctx, supplier, id)
}
