// Code generated by MockGen. DO NOT EDIT.
// Source: table_repository.go
//
// Generated by this command:
//
//	mockgen -source=table_repository.go -destination=../data/mock/table_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTableRepository is a mock of TableRepository interface.
type MockTableRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTableRepositoryMockRecorder
	isgomock struct{}
}

// MockTableRepositoryMockRecorder is the mock recorder for MockTableRepository.
type MockTableRepositoryMockRecorder struct {
	mock *MockTableRepository
}

// NewMockTableRepository creates a new mock instance.
func NewMockTableRepository(ctrl *gomock.Controller) *MockTableRepository {
	mock := &MockTableRepository{ctrl: ctrl}
	mock.recorder = &MockTableRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableRepository) EXPECT() *MockTableRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockTableRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockTableRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockTableRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateTable mocks base method.
func (m *MockTableRepository) CreateTable(ctx context.Context, table domain.Table) (domain.Table, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTable", ctx, table)
	ret0, _ := ret[0].(domain.Table)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateTable indicates an expected call of CreateTable.
func (mr *MockTableRepositoryMockRecorder) CreateTable(ctx, table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTable", reflect.TypeOf((*MockTableRepository)(nil).CreateTable), ctx, table)
}

// DeleteTableById mocks base method.
func (m *MockTableRepository) DeleteTableById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTableById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteTableById indicates an expected call of DeleteTableById.
func (mr *MockTableRepositoryMockRecorder) DeleteTableById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTableById", reflect.TypeOf((*MockTableRepository)(nil).DeleteTableById), ctx, id)
}

// GetTableByCode mocks base method.
func (m *MockTableRepository) GetTableByCode(ctx context.Context, code string) (domain.Table, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableByCode", ctx, code)
	ret0, _ := ret[0].(domain.Table)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTableByCode indicates an expected call of GetTableByCode.
func (mr *MockTableRepositoryMockRecorder) GetTableByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableByCode", reflect.TypeOf((*MockTableRepository)(nil).GetTableByCode), ctx, code)
}

// GetTableById mocks base method.
func (m *MockTableRepository) GetTableById(ctx context.Context, id int64) (domain.Table, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableById", ctx, id)
	ret0, _ := ret[0].(domain.Table)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTableById indicates an expected call of GetTableById.
func (mr *MockTableRepositoryMockRecorder) GetTableById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableById", reflect.TypeOf((*MockTableRepository)(nil).GetTableById), ctx, id)
}

// GetTableByLabel mocks base method.
func (m *MockTableRepository) GetTableByLabel(ctx context.Context, label string) (domain.Table, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableByLabel", ctx, label)
	ret0, _ := ret[0].(domain.Table)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTableByLabel indicates an expected call of GetTableByLabel.
func (mr *MockTableRepositoryMockRecorder) GetTableByLabel(ctx, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableByLabel", reflect.TypeOf((*MockTableRepository)(nil).GetTableByLabel), ctx, label)
}

// GetTableList mocks base method.
func (m *MockTableRepository) GetTableList(ctx context.Context) ([]domain.Table, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableList", ctx)
	ret0, _ := ret[0].([]domain.Table)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTableList indicates an expected call of GetTableList.
func (mr *MockTableRepositoryMockRecorder) GetTableList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableList", reflect.TypeOf((*MockTableRepository)(nil).GetTableList), ctx)
}

// UpdateTableById mocks base method.
func (m *MockTableRepository) UpdateTableById(ctx context.Context, table domain.Table, id int64) (domain.Table, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTableById", ctx, table, id)
	ret0, _ := ret[0].(domain.Table)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateTableById indicates an expected call of UpdateTableById.
func (mr *MockTableRepositoryMockRecorder) UpdateTableById(ctx, table, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTableById", reflect.TypeOf((*MockTableRepository)(nil).UpdateTableById), ctx, table, id)
}
