// Code generated by MockGen. DO NOT EDIT.
// Source: tag_repository.go
//
// Generated by this command:
//
//	mockgen -source=tag_repository.go -destination=../data/mock/tag_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockTagRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockTagRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockTagRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateTag mocks base method.
func (m *MockTagRepository) CreateTag(ctx context.Context, tag domain.Tag) (domain.Tag, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, tag)
	ret0, _ := ret[0].(domain.Tag)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockTagRepositoryMockRecorder) CreateTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockTagRepository)(nil).CreateTag), ctx, tag)
}

// DeleteTagById mocks base method.
func (m *MockTagRepository) DeleteTagById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTagById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteTagById indicates an expected call of DeleteTagById.
func (mr *MockTagRepositoryMockRecorder) DeleteTagById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTagById", reflect.TypeOf((*MockTagRepository)(nil).DeleteTagById), ctx, id)
}

// GetTagById mocks base method.
func (m *MockTagRepository) GetTagById(ctx context.Context, id int64) (domain.Tag, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagById", ctx, id)
	ret0, _ := ret[0].(domain.Tag)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTagById indicates an expected call of GetTagById.
func (mr *MockTagRepositoryMockRecorder) GetTagById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagById", reflect.TypeOf((*MockTagRepository)(nil).GetTagById), ctx, id)
}

// GetTagList mocks base method.
func (m *MockTagRepository) GetTagList(ctx context.Context) ([]domain.Tag, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagList", ctx)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTagList indicates an expected call of GetTagList.
func (mr *MockTagRepositoryMockRecorder) GetTagList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagList", reflect.TypeOf((*MockTagRepository)(nil).GetTagList), ctx)
}

// UpdateTagById mocks base method.
func (m *MockTagRepository) UpdateTagById(ctx context.Context, tag domain.Tag, id int64) (domain.Tag, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTagById", ctx, tag, id)
	ret0, _ := ret[0].(domain.Tag)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateTagById indicates an expected call of UpdateTagById.
func (mr *MockTagRepositoryMockRecorder) UpdateTagById(ctx, tag, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTagById", reflect.TypeOf((*MockTagRepository)(nil).UpdateTagById), ctx, tag, id)
}
