// Code generated by MockGen. DO NOT EDIT.
// Source: ticket_repository.go
//
// Generated by this command:
//
//	mockgen -source=ticket_repository.go -destination=../data/mock/ticket_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTicketRepository is a mock of TicketRepository interface.
type MockTicketRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTicketRepositoryMockRecorder
	isgomock struct{}
}

// MockTicketRepositoryMockRecorder is the mock recorder for MockTicketRepository.
type MockTicketRepositoryMockRecorder struct {
	mock *MockTicketRepository
}

// NewMockTicketRepository creates a new mock instance.
func NewMockTicketRepository(ctrl *gomock.Controller) *MockTicketRepository {
	mock := &MockTicketRepository{ctrl: ctrl}
	mock.recorder = &MockTicketRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketRepository) EXPECT() *MockTicketRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockTicketRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockTicketRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockTicketRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateTicket mocks base method.
func (m *MockTicketRepository) CreateTicket(ctx context.Context, ticket domain.Ticket) (domain.Ticket, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicket", ctx, ticket)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MockTicketRepositoryMockRecorder) CreateTicket(ctx, ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MockTicketRepository)(nil).CreateTicket), ctx, ticket)
}

// DeleteTicketById mocks base method.
func (m *MockTicketRepository) DeleteTicketById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTicketById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteTicketById indicates an expected call of DeleteTicketById.
func (mr *MockTicketRepositoryMockRecorder) DeleteTicketById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTicketById", reflect.TypeOf((*MockTicketRepository)(nil).DeleteTicketById), ctx, id)
}

// GetTicketByCode mocks base method.
func (m *MockTicketRepository) GetTicketByCode(ctx context.Context, code string) (domain.Ticket, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketByCode", ctx, code)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTicketByCode indicates an expected call of GetTicketByCode.
func (mr *MockTicketRepositoryMockRecorder) GetTicketByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketByCode", reflect.TypeOf((*MockTicketRepository)(nil).GetTicketByCode), ctx, code)
}

// GetTicketById mocks base method.
func (m *MockTicketRepository) GetTicketById(ctx context.Context, id int64) (domain.Ticket, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketById", ctx, id)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTicketById indicates an expected call of GetTicketById.
func (mr *MockTicketRepositoryMockRecorder) GetTicketById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketById", reflect.TypeOf((*MockTicketRepository)(nil).GetTicketById), ctx, id)
}

// GetTicketByName mocks base method.
func (m *MockTicketRepository) GetTicketByName(ctx context.Context, name string) (domain.Ticket, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketByName", ctx, name)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTicketByName indicates an expected call of GetTicketByName.
func (mr *MockTicketRepositoryMockRecorder) GetTicketByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketByName", reflect.TypeOf((*MockTicketRepository)(nil).GetTicketByName), ctx, name)
}

// GetTicketList mocks base method.
func (m *MockTicketRepository) GetTicketList(ctx context.Context) ([]domain.Ticket, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketList", ctx)
	ret0, _ := ret[0].([]domain.Ticket)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTicketList indicates an expected call of GetTicketList.
func (mr *MockTicketRepositoryMockRecorder) GetTicketList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketList", reflect.TypeOf((*MockTicketRepository)(nil).GetTicketList), ctx)
}

// UpdateTicketById mocks base method.
func (m *MockTicketRepository) UpdateTicketById(ctx context.Context, ticket domain.Ticket, id int64) (domain.Ticket, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTicketById", ctx, ticket, id)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateTicketById indicates an expected call of UpdateTicketById.
func (mr *MockTicketRepositoryMockRecorder) UpdateTicketById(ctx, ticket, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTicketById", reflect.TypeOf((*MockTicketRepository)(nil).UpdateTicketById), ctx, ticket, id)
}
