// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_repository.go
//
// Generated by this command:
//
//	mockgen -source=transaction_repository.go -destination=../data/mock/transaction_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockTransactionRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockTransactionRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateTransaction mocks base method.
func (m *MockTransactionRepository) CreateTransaction(ctx context.Context, transaction domain.Transaction) (domain.Transaction, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, transaction)
	ret0, _ := ret[0].(domain.Transaction)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionRepositoryMockRecorder) CreateTransaction(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).CreateTransaction), ctx, transaction)
}

// DeleteTransactionById mocks base method.
func (m *MockTransactionRepository) DeleteTransactionById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransactionById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteTransactionById indicates an expected call of DeleteTransactionById.
func (mr *MockTransactionRepositoryMockRecorder) DeleteTransactionById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransactionById", reflect.TypeOf((*MockTransactionRepository)(nil).DeleteTransactionById), ctx, id)
}

// GetTransactionById mocks base method.
func (m *MockTransactionRepository) GetTransactionById(ctx context.Context, id int64) (domain.Transaction, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionById", ctx, id)
	ret0, _ := ret[0].(domain.Transaction)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTransactionById indicates an expected call of GetTransactionById.
func (mr *MockTransactionRepositoryMockRecorder) GetTransactionById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionById", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransactionById), ctx, id)
}

// GetTransactionList mocks base method.
func (m *MockTransactionRepository) GetTransactionList(ctx context.Context, query string, sortBy domain.SortBy, order domain.Order, skip, limit int, paymentStatus domain.PaymentStatus, walletId *int) ([]domain.Transaction, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionList", ctx, query, sortBy, order, skip, limit, paymentStatus, walletId)
	ret0, _ := ret[0].([]domain.Transaction)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTransactionList indicates an expected call of GetTransactionList.
func (mr *MockTransactionRepositoryMockRecorder) GetTransactionList(ctx, query, sortBy, order, skip, limit, paymentStatus, walletId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionList", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransactionList), ctx, query, sortBy, order, skip, limit, paymentStatus, walletId)
}

// GetTransactionListTotal mocks base method.
func (m *MockTransactionRepository) GetTransactionListTotal(ctx context.Context, query string, paymentStatus domain.PaymentStatus, walletId *int) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionListTotal", ctx, query, paymentStatus, walletId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTransactionListTotal indicates an expected call of GetTransactionListTotal.
func (mr *MockTransactionRepositoryMockRecorder) GetTransactionListTotal(ctx, query, paymentStatus, walletId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionListTotal", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransactionListTotal), ctx, query, paymentStatus, walletId)
}

// GetTransactionStatistics mocks base method.
func (m *MockTransactionRepository) GetTransactionStatistics(ctx context.Context, groupBy string) ([]domain.TransactionStatistic, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionStatistics", ctx, groupBy)
	ret0, _ := ret[0].([]domain.TransactionStatistic)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetTransactionStatistics indicates an expected call of GetTransactionStatistics.
func (mr *MockTransactionRepositoryMockRecorder) GetTransactionStatistics(ctx, groupBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionStatistics", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransactionStatistics), ctx, groupBy)
}

// PayTransaction mocks base method.
func (m *MockTransactionRepository) PayTransaction(ctx context.Context, walletId int64, paidAt time.Time, paidAmount float32, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayTransaction", ctx, walletId, paidAt, paidAmount, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// PayTransaction indicates an expected call of PayTransaction.
func (mr *MockTransactionRepositoryMockRecorder) PayTransaction(ctx, walletId, paidAt, paidAmount, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).PayTransaction), ctx, walletId, paidAt, paidAmount, id)
}

// UnpayTransaction mocks base method.
func (m *MockTransactionRepository) UnpayTransaction(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpayTransaction", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// UnpayTransaction indicates an expected call of UnpayTransaction.
func (mr *MockTransactionRepositoryMockRecorder) UnpayTransaction(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpayTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).UnpayTransaction), ctx, id)
}

// UpdateTransactionById mocks base method.
func (m *MockTransactionRepository) UpdateTransactionById(ctx context.Context, transaction domain.Transaction, id int64) (domain.Transaction, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionById", ctx, transaction, id)
	ret0, _ := ret[0].(domain.Transaction)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateTransactionById indicates an expected call of UpdateTransactionById.
func (mr *MockTransactionRepositoryMockRecorder) UpdateTransactionById(ctx, transaction, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionById", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateTransactionById), ctx, transaction, id)
}
