// Code generated by MockGen. DO NOT EDIT.
// Source: variant_repository.go
//
// Generated by this command:
//
//	mockgen -source=variant_repository.go -destination=../data/mock/variant_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVariantRepository is a mock of VariantRepository interface.
type MockVariantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVariantRepositoryMockRecorder
	isgomock struct{}
}

// MockVariantRepositoryMockRecorder is the mock recorder for MockVariantRepository.
type MockVariantRepositoryMockRecorder struct {
	mock *MockVariantRepository
}

// NewMockVariantRepository creates a new mock instance.
func NewMockVariantRepository(ctrl *gomock.Controller) *MockVariantRepository {
	mock := &MockVariantRepository{ctrl: ctrl}
	mock.recorder = &MockVariantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVariantRepository) EXPECT() *MockVariantRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockVariantRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockVariantRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockVariantRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateVariant mocks base method.
func (m *MockVariantRepository) CreateVariant(ctx context.Context, variant domain.Variant) (domain.Variant, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVariant", ctx, variant)
	ret0, _ := ret[0].(domain.Variant)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateVariant indicates an expected call of CreateVariant.
func (mr *MockVariantRepositoryMockRecorder) CreateVariant(ctx, variant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVariant", reflect.TypeOf((*MockVariantRepository)(nil).CreateVariant), ctx, variant)
}

// DeleteVariantById mocks base method.
func (m *MockVariantRepository) DeleteVariantById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVariantById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteVariantById indicates an expected call of DeleteVariantById.
func (mr *MockVariantRepositoryMockRecorder) DeleteVariantById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVariantById", reflect.TypeOf((*MockVariantRepository)(nil).DeleteVariantById), ctx, id)
}

// GetVariantById mocks base method.
func (m *MockVariantRepository) GetVariantById(ctx context.Context, id int64) (domain.Variant, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariantById", ctx, id)
	ret0, _ := ret[0].(domain.Variant)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetVariantById indicates an expected call of GetVariantById.
func (mr *MockVariantRepositoryMockRecorder) GetVariantById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariantById", reflect.TypeOf((*MockVariantRepository)(nil).GetVariantById), ctx, id)
}

// GetVariantList mocks base method.
func (m *MockVariantRepository) GetVariantList(ctx context.Context, query string, sortBy domain.SortBy, order domain.Order, skip, limit int, productId *int, optionValues []int) ([]domain.Variant, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariantList", ctx, query, sortBy, order, skip, limit, productId, optionValues)
	ret0, _ := ret[0].([]domain.Variant)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetVariantList indicates an expected call of GetVariantList.
func (mr *MockVariantRepositoryMockRecorder) GetVariantList(ctx, query, sortBy, order, skip, limit, productId, optionValues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariantList", reflect.TypeOf((*MockVariantRepository)(nil).GetVariantList), ctx, query, sortBy, order, skip, limit, productId, optionValues)
}

// GetVariantListTotal mocks base method.
func (m *MockVariantRepository) GetVariantListTotal(ctx context.Context, query string) (int64, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVariantListTotal", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetVariantListTotal indicates an expected call of GetVariantListTotal.
func (mr *MockVariantRepositoryMockRecorder) GetVariantListTotal(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVariantListTotal", reflect.TypeOf((*MockVariantRepository)(nil).GetVariantListTotal), ctx, query)
}

// UpdateVariantById mocks base method.
func (m *MockVariantRepository) UpdateVariantById(ctx context.Context, variant domain.Variant, id int64) (domain.Variant, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariantById", ctx, variant, id)
	ret0, _ := ret[0].(domain.Variant)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateVariantById indicates an expected call of UpdateVariantById.
func (mr *MockVariantRepositoryMockRecorder) UpdateVariantById(ctx, variant, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariantById", reflect.TypeOf((*MockVariantRepository)(nil).UpdateVariantById), ctx, variant, id)
}
