// Code generated by MockGen. DO NOT EDIT.
// Source: wallet_repository.go
//
// Generated by this command:
//
//	mockgen -source=wallet_repository.go -destination=../data/mock/wallet_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWalletRepository is a mock of WalletRepository interface.
type MockWalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepositoryMockRecorder
	isgomock struct{}
}

// MockWalletRepositoryMockRecorder is the mock recorder for MockWalletRepository.
type MockWalletRepositoryMockRecorder struct {
	mock *MockWalletRepository
}

// NewMockWalletRepository creates a new mock instance.
func NewMockWalletRepository(ctrl *gomock.Controller) *MockWalletRepository {
	mock := &MockWalletRepository{ctrl: ctrl}
	mock.recorder = &MockWalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepository) EXPECT() *MockWalletRepositoryMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockWalletRepository) BeginTransaction(ctx context.Context, callback func(context.Context) *domain.Error) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", ctx, callback)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockWalletRepositoryMockRecorder) BeginTransaction(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockWalletRepository)(nil).BeginTransaction), ctx, callback)
}

// CreateWallet mocks base method.
func (m *MockWalletRepository) CreateWallet(ctx context.Context, wallet domain.Wallet) (domain.Wallet, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, wallet)
	ret0, _ := ret[0].(domain.Wallet)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockWalletRepositoryMockRecorder) CreateWallet(ctx, wallet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockWalletRepository)(nil).CreateWallet), ctx, wallet)
}

// CreateWalletTransfer mocks base method.
func (m *MockWalletRepository) CreateWalletTransfer(ctx context.Context, walletTransfer domain.WalletTransfer, fromWalletId int64) (domain.WalletTransfer, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWalletTransfer", ctx, walletTransfer, fromWalletId)
	ret0, _ := ret[0].(domain.WalletTransfer)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// CreateWalletTransfer indicates an expected call of CreateWalletTransfer.
func (mr *MockWalletRepositoryMockRecorder) CreateWalletTransfer(ctx, walletTransfer, fromWalletId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWalletTransfer", reflect.TypeOf((*MockWalletRepository)(nil).CreateWalletTransfer), ctx, walletTransfer, fromWalletId)
}

// DeleteWalletById mocks base method.
func (m *MockWalletRepository) DeleteWalletById(ctx context.Context, id int64) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWalletById", ctx, id)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// DeleteWalletById indicates an expected call of DeleteWalletById.
func (mr *MockWalletRepositoryMockRecorder) DeleteWalletById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWalletById", reflect.TypeOf((*MockWalletRepository)(nil).DeleteWalletById), ctx, id)
}

// GetWalletById mocks base method.
func (m *MockWalletRepository) GetWalletById(ctx context.Context, id int64) (domain.Wallet, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletById", ctx, id)
	ret0, _ := ret[0].(domain.Wallet)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetWalletById indicates an expected call of GetWalletById.
func (mr *MockWalletRepositoryMockRecorder) GetWalletById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletById", reflect.TypeOf((*MockWalletRepository)(nil).GetWalletById), ctx, id)
}

// GetWalletList mocks base method.
func (m *MockWalletRepository) GetWalletList(ctx context.Context) ([]domain.Wallet, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletList", ctx)
	ret0, _ := ret[0].([]domain.Wallet)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetWalletList indicates an expected call of GetWalletList.
func (mr *MockWalletRepositoryMockRecorder) GetWalletList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletList", reflect.TypeOf((*MockWalletRepository)(nil).GetWalletList), ctx)
}

// GetWalletTransferList mocks base method.
func (m *MockWalletRepository) GetWalletTransferList(ctx context.Context, walletId int64, sortBy domain.SortBy, order domain.Order, skip, limit int) ([]domain.WalletTransfer, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletTransferList", ctx, walletId, sortBy, order, skip, limit)
	ret0, _ := ret[0].([]domain.WalletTransfer)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetWalletTransferList indicates an expected call of GetWalletTransferList.
func (mr *MockWalletRepositoryMockRecorder) GetWalletTransferList(ctx, walletId, sortBy, order, skip, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletTransferList", reflect.TypeOf((*MockWalletRepository)(nil).GetWalletTransferList), ctx, walletId, sortBy, order, skip, limit)
}

// UpdateWalletById mocks base method.
func (m *MockWalletRepository) UpdateWalletById(ctx context.Context, wallet domain.Wallet, id int64) (domain.Wallet, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWalletById", ctx, wallet, id)
	ret0, _ := ret[0].(domain.Wallet)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// UpdateWalletById indicates an expected call of UpdateWalletById.
func (mr *MockWalletRepositoryMockRecorder) UpdateWalletById(ctx, wallet, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWalletById", reflect.TypeOf((*MockWalletRepository)(nil).UpdateWalletById), ctx, wallet, id)
}
