// Code generated by MockGen. DO NOT EDIT.
// Source: web_push_subscription_repository.go
//
// Generated by this command:
//
//	mockgen -source=web_push_subscription_repository.go -destination=../data/mock/web_push_subscription_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWebPushSubscriptionRepository is a mock of WebPushSubscriptionRepository interface.
type MockWebPushSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebPushSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockWebPushSubscriptionRepositoryMockRecorder is the mock recorder for MockWebPushSubscriptionRepository.
type MockWebPushSubscriptionRepositoryMockRecorder struct {
	mock *MockWebPushSubscriptionRepository
}

// NewMockWebPushSubscriptionRepository creates a new mock instance.
func NewMockWebPushSubscriptionRepository(ctrl *gomock.Controller) *MockWebPushSubscriptionRepository {
	mock := &MockWebPushSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockWebPushSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPushSubscriptionRepository) EXPECT() *MockWebPushSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// GetWebPushSubscriptionsBySessionId mocks base method.
func (m *MockWebPushSubscriptionRepository) GetWebPushSubscriptionsBySessionId(ctx context.Context, sessionId string) ([]domain.WebPushSubscription, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebPushSubscriptionsBySessionId", ctx, sessionId)
	ret0, _ := ret[0].([]domain.WebPushSubscription)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// GetWebPushSubscriptionsBySessionId indicates an expected call of GetWebPushSubscriptionsBySessionId.
func (mr *MockWebPushSubscriptionRepositoryMockRecorder) GetWebPushSubscriptionsBySessionId(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebPushSubscriptionsBySessionId", reflect.TypeOf((*MockWebPushSubscriptionRepository)(nil).GetWebPushSubscriptionsBySessionId), ctx, sessionId)
}

// SubscribeWebPush mocks base method.
func (m *MockWebPushSubscriptionRepository) SubscribeWebPush(ctx context.Context, subscription domain.WebPushSubscription) (domain.WebPushSubscription, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeWebPush", ctx, subscription)
	ret0, _ := ret[0].(domain.WebPushSubscription)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// SubscribeWebPush indicates an expected call of SubscribeWebPush.
func (mr *MockWebPushSubscriptionRepositoryMockRecorder) SubscribeWebPush(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeWebPush", reflect.TypeOf((*MockWebPushSubscriptionRepository)(nil).SubscribeWebPush), ctx, subscription)
}

// UnsubscribeWebPush mocks base method.
func (m *MockWebPushSubscriptionRepository) UnsubscribeWebPush(ctx context.Context, sessionId, endpoint string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeWebPush", ctx, sessionId, endpoint)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// UnsubscribeWebPush indicates an expected call of UnsubscribeWebPush.
func (mr *MockWebPushSubscriptionRepositoryMockRecorder) UnsubscribeWebPush(ctx, sessionId, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeWebPush", reflect.TypeOf((*MockWebPushSubscriptionRepository)(nil).UnsubscribeWebPush), ctx, sessionId, endpoint)
}
