// Code generated by MockGen. DO NOT EDIT.
// Source: web_push_gateway_repository.go
//
// Generated by this command:
//
//	mockgen -source=web_push_gateway_repository.go -destination=../data/mock/web_push_gateway_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWebPushGatewayRepository is a mock of WebPushGatewayRepository interface.
type MockWebPushGatewayRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebPushGatewayRepositoryMockRecorder
}

// MockWebPushGatewayRepositoryMockRecorder is the mock recorder for MockWebPushGatewayRepository.
type MockWebPushGatewayRepositoryMockRecorder struct {
	mock *MockWebPushGatewayRepository
}

// NewMockWebPushGatewayRepository creates a new mock instance.
func NewMockWebPushGatewayRepository(ctrl *gomock.Controller) *MockWebPushGatewayRepository {
	mock := &MockWebPushGatewayRepository{ctrl: ctrl}
	mock.recorder = &MockWebPushGatewayRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebPushGatewayRepository) EXPECT() *MockWebPushGatewayRepositoryMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockWebPushGatewayRepository) Send(ctx context.Context, messages []domain.WebPushMessage) ([]domain.WebPushReceipt, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, messages)
	ret0, _ := ret[0].([]domain.WebPushReceipt)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockWebPushGatewayRepositoryMockRecorder) Send(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWebPushGatewayRepository)(nil).Send), ctx, messages)
}
