// Code generated by MockGen. DO NOT EDIT.
// Source: whatsapp_number_verification_usecase.go
//
// Generated by this command:
//
//	mockgen -source=whatsapp_number_verification_usecase.go -destination=../data/mock/whatsapp_number_verifier.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWhatsappNumberVerifier is a mock of WhatsappNumberVerifier interface.
type MockWhatsappNumberVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsappNumberVerifierMockRecorder
	isgomock struct{}
}

// MockWhatsappNumberVerifierMockRecorder is the mock recorder for MockWhatsappNumberVerifier.
type MockWhatsappNumberVerifierMockRecorder struct {
	mock *MockWhatsappNumberVerifier
}

// NewMockWhatsappNumberVerifier creates a new mock instance.
func NewMockWhatsappNumberVerifier(ctrl *gomock.Controller) *MockWhatsappNumberVerifier {
	mock := &MockWhatsappNumberVerifier{ctrl: ctrl}
	mock.recorder = &MockWhatsappNumberVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsappNumberVerifier) EXPECT() *MockWhatsappNumberVerifierMockRecorder {
	return m.recorder
}

// EnsureRegistered mocks base method.
func (m *MockWhatsappNumberVerifier) EnsureRegistered(ctx context.Context, normalizedNumber string) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureRegistered", ctx, normalizedNumber)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// EnsureRegistered indicates an expected call of EnsureRegistered.
func (mr *MockWhatsappNumberVerifierMockRecorder) EnsureRegistered(ctx, normalizedNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureRegistered", reflect.TypeOf((*MockWhatsappNumberVerifier)(nil).EnsureRegistered), ctx, normalizedNumber)
}
