// Code generated by MockGen. DO NOT EDIT.
// Source: whatsapp_gateway_repository.go
//
// Generated by this command:
//
//	mockgen -source=whatsapp_gateway_repository.go -destination=../data/mock/whatsapp_gateway_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWhatsAppGatewayRepository is a mock of WhatsAppGatewayRepository interface.
type MockWhatsAppGatewayRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppGatewayRepositoryMockRecorder
	isgomock struct{}
}

// MockWhatsAppGatewayRepositoryMockRecorder is the mock recorder for MockWhatsAppGatewayRepository.
type MockWhatsAppGatewayRepositoryMockRecorder struct {
	mock *MockWhatsAppGatewayRepository
}

// NewMockWhatsAppGatewayRepository creates a new mock instance.
func NewMockWhatsAppGatewayRepository(ctrl *gomock.Controller) *MockWhatsAppGatewayRepository {
	mock := &MockWhatsAppGatewayRepository{ctrl: ctrl}
	mock.recorder = &MockWhatsAppGatewayRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsAppGatewayRepository) EXPECT() *MockWhatsAppGatewayRepositoryMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockWhatsAppGatewayRepository) Send(ctx context.Context, message domain.WhatsAppMessage) (domain.WhatsAppSendResult, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, message)
	ret0, _ := ret[0].(domain.WhatsAppSendResult)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockWhatsAppGatewayRepositoryMockRecorder) Send(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWhatsAppGatewayRepository)(nil).Send), ctx, message)
}

// ValidateNumber mocks base method.
func (m *MockWhatsAppGatewayRepository) ValidateNumber(ctx context.Context, number string) (domain.WhatsAppNumberValidationResult, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateNumber", ctx, number)
	ret0, _ := ret[0].(domain.WhatsAppNumberValidationResult)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// ValidateNumber indicates an expected call of ValidateNumber.
func (mr *MockWhatsAppGatewayRepositoryMockRecorder) ValidateNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateNumber", reflect.TypeOf((*MockWhatsAppGatewayRepository)(nil).ValidateNumber), ctx, number)
}
