// Code generated by MockGen. DO NOT EDIT.
// Source: whatsapp_number_verification_repository.go
//
// Generated by this command:
//
//	mockgen -source=whatsapp_number_verification_repository.go -destination=../data/mock/whatsapp_number_verification_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "apps/api/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockWhatsappNumberVerificationRepository is a mock of WhatsappNumberVerificationRepository interface.
type MockWhatsappNumberVerificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsappNumberVerificationRepositoryMockRecorder
	isgomock struct{}
}

// MockWhatsappNumberVerificationRepositoryMockRecorder is the mock recorder for MockWhatsappNumberVerificationRepository.
type MockWhatsappNumberVerificationRepositoryMockRecorder struct {
	mock *MockWhatsappNumberVerificationRepository
}

// NewMockWhatsappNumberVerificationRepository creates a new mock instance.
func NewMockWhatsappNumberVerificationRepository(ctrl *gomock.Controller) *MockWhatsappNumberVerificationRepository {
	mock := &MockWhatsappNumberVerificationRepository{ctrl: ctrl}
	mock.recorder = &MockWhatsappNumberVerificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsappNumberVerificationRepository) EXPECT() *MockWhatsappNumberVerificationRepositoryMockRecorder {
	return m.recorder
}

// IsWhatsappNumberVerified mocks base method.
func (m *MockWhatsappNumberVerificationRepository) IsWhatsappNumberVerified(ctx context.Context, whatsappNumber string) (bool, *domain.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWhatsappNumberVerified", ctx, whatsappNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*domain.Error)
	return ret0, ret1
}

// IsWhatsappNumberVerified indicates an expected call of IsWhatsappNumberVerified.
func (mr *MockWhatsappNumberVerificationRepositoryMockRecorder) IsWhatsappNumberVerified(ctx, whatsappNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWhatsappNumberVerified", reflect.TypeOf((*MockWhatsappNumberVerificationRepository)(nil).IsWhatsappNumberVerified), ctx, whatsappNumber)
}

// MarkWhatsappNumberVerified mocks base method.
func (m *MockWhatsappNumberVerificationRepository) MarkWhatsappNumberVerified(ctx context.Context, whatsappNumber string, verifiedAt time.Time) *domain.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkWhatsappNumberVerified", ctx, whatsappNumber, verifiedAt)
	ret0, _ := ret[0].(*domain.Error)
	return ret0
}

// MarkWhatsappNumberVerified indicates an expected call of MarkWhatsappNumberVerified.
func (mr *MockWhatsappNumberVerificationRepositoryMockRecorder) MarkWhatsappNumberVerified(ctx, whatsappNumber, verifiedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkWhatsappNumberVerified", reflect.TypeOf((*MockWhatsappNumberVerificationRepository)(nil).MarkWhatsappNumberVerified), ctx, whatsappNumber, verifiedAt)
}
