import React from 'react';

const NullIcon: React.FC<Record<string, unknown>> = () => null;

export const AlertCircle = NullIcon;
export const ArrowLeft = NullIcon;
export const Box = NullIcon;
export const Calendar = NullIcon;
export const Check = NullIcon;
export const CheckCircle = NullIcon;
export const ChevronDown = NullIcon;
export const ChevronLeft = NullIcon;
export const ChevronRight = NullIcon;
export const ChevronUp = NullIcon;
export const ChevronsLeft = NullIcon;
export const ChevronsRight = NullIcon;
export const Clock = NullIcon;
export const CreditCard = NullIcon;
export const Eye = NullIcon;
export const Filter = NullIcon;
export const Map = NullIcon;
export const MapPin = NullIcon;
export const Minus = NullIcon;
export const MinusSquare = NullIcon;
export const MoreVertical = NullIcon;
export const Pencil = NullIcon;
export const PercentSquare = NullIcon;
export const Phone = NullIcon;
export const Plus = NullIcon;
export const QrCode = NullIcon;
export const Separator = NullIcon;
export const ShoppingCart = NullIcon;
export const Tag = NullIcon;
export const Trash = NullIcon;
export const Wallet = NullIcon;
export const User = NullIcon;
export const X = NullIcon;
export const ConciergeBell = NullIcon;
export const DollarSign = NullIcon;
export const Printer = NullIcon;
export const XCircle = NullIcon;
