name: Deploy Web
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t gatherloop/gatherloop-pos-web -f apps/web/Dockerfile --build-arg API_BASE_URL=${{ secrets.API_BASE_URL }} .
      - run: docker push gatherloop/gatherloop-pos-web
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            docker pull gatherloop/gatherloop-pos-web
            docker container stop gatherloop-pos-web
            docker container remove gatherloop-pos-web
            docker run --name gatherloop-pos-web -p 3000:3000 -d gatherloop/gatherloop-pos-web
