name: Deploy API
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: npx nx run api:image:build
      - run: npx nx run api:image:push
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            docker pull gatherloop/gatherloop-pos-api
            docker container stop gatherloop-pos-api
            docker container remove gatherloop-pos-api 
            docker run --name gatherloop-pos-api --network gatherloop-pos-network -e DB_USERNAME=${{ secrets.DB_USERNAME }} -e "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" -e DB_NAME=${{ secrets.DB_NAME }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e PORT=${{ secrets.API_PORT }} -p ${{ secrets.API_PORT }}:${{ secrets.API_PORT }} -d gatherloop/gatherloop-pos-api
